### ISSUE TITLE
Mouse focus wonky when moving mouse between screens

### ISSUE THREAD

**Issue by tbreslein** [qtile/qtile#1735] opened 2020-05-17 10:29 UTC
# Issue description

When moving the mouse from one screen (i.e. monitor) to another, sometimes the focus changes, even though `follow_mouse_focus` is turned off. The expected behaviour would obviously be that the focus does not change at all. What is really weird is the "sometimes" bit - I would say it's about 50/50 whether the focus changes or not. Sometimes the focus changes 'backwards', as in the window my mouse just LEFT gains focus. Here are the possibly relevant options:

```
follow_mouse_focus = False
bring_front_click = False
cursor_warp = False
focus_on_window_activation = "smart"
```

When moving the mouse just on one screen, the behaviour is as expected: The focus does not change (since I turned that off); it just happens (sometimes) when moving from one screen to another).

The behaviour is the same for all layouts I tested, which are `monadtall`, `stack`, `verticaltile`, and `max`.

# Qtile version

0.15.1
commit hash: `ba771babb868d4f06914a28f44f8d2639c7d2e47`

# Stack traces

`xsession-errors` is empty.

`qtile.log` (most are warnings about modules he cannot load which is a whole other issue, which does not bother me though, since I do not use those widgets anyways, so I posted a shortened log below, where those warnings have been thrown out):

```
2020-05-17 11:50:07,404 WARNING libqtile manager.py:loop():L245 Restarting Qtile with os.execv(...)
2020-05-17 11:50:07,568 WARNING libqtile xcursors.py:_setup_xcursor_binding():L112 xcb-cursor not found, fallback to font pointer
2020-05-17 11:50:07,640 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.CPUGraph', No module named 'psutil'
2020-05-17 11:50:07,640 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.MemoryGraph', No module named 'psutil'
2020-05-17 11:50:07,641 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.SwapGraph', No module named 'psutil'
2020-05-17 11:50:07,641 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.NetGraph', No module named 'psutil'
2020-05-17 11:50:07,641 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.HDDGraph', No module named 'psutil'
2020-05-17 11:50:07,642 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.HDDBusyGraph', No module named 'psutil'
2020-05-17 11:50:07,657 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.launchbar.LaunchBar', No module named 'xdg'
2020-05-17 11:50:07,658 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2020-05-17 11:50:07,660 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2020-05-17 11:50:07,660 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
2020-05-17 11:50:07,661 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2020-05-17 11:50:07,661 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.net.Net', No module named 'psutil'
2020-05-17 11:50:07,662 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.memory.Memory', No module named 'psutil'
2020-05-17 11:50:07,663 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.cpu.CPU', No module named 'psutil'
2020-05-17 11:50:11,147 WARNING libqtile manager.py:loop():L245 Restarting Qtile with os.execv(...)
2020-05-17 11:50:11,316 WARNING libqtile xcursors.py:_setup_xcursor_binding():L112 xcb-cursor not found, fallback to font pointer
2020-05-17 11:50:11,388 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.CPUGraph', No module named 'psutil'
2020-05-17 11:50:11,389 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.MemoryGraph', No module named 'psutil'
2020-05-17 11:50:11,389 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.SwapGraph', No module named 'psutil'
2020-05-17 11:50:11,390 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.NetGraph', No module named 'psutil'
2020-05-17 11:50:11,390 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.HDDGraph', No module named 'psutil'
2020-05-17 11:50:11,390 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.graph.HDDBusyGraph', No module named 'psutil'
2020-05-17 11:50:11,405 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.launchbar.LaunchBar', No module named 'xdg'
2020-05-17 11:50:11,406 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2020-05-17 11:50:11,408 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2020-05-17 11:50:11,409 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
2020-05-17 11:50:11,409 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2020-05-17 11:50:11,410 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.net.Net', No module named 'psutil'
2020-05-17 11:50:11,411 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.memory.Memory', No module named 'psutil'
2020-05-17 11:50:11,411 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.cpu.CPU', No module named 'psutil'
2020-05-17 11:53:01,214 WARNING libqtile xcbq.py:set_property():L687 X error in SetProperty (wid=41943042, prop='WM_STATE'), ignoring
2020-05-17 12:15:38,082 WARNING libqtile xcbq.py:set_property():L687 X error in SetProperty (wid=41943042, prop='WM_STATE'), ignoring
```
shorter version of the log:

```
2020-05-17 11:50:07,404 WARNING libqtile manager.py:loop():L245 Restarting Qtile with os.execv(...)
2020-05-17 11:50:07,568 WARNING libqtile xcursors.py:_setup_xcursor_binding():L112 xcb-cursor not found, fallback to font pointer
... unmet dependencies ...
2020-05-17 11:50:11,147 WARNING libqtile manager.py:loop():L245 Restarting Qtile with os.execv(...)
2020-05-17 11:50:11,316 WARNING libqtile xcursors.py:_setup_xcursor_binding():L112 xcb-cursor not found, fallback to font pointer
... unmet dependencies ...
2020-05-17 11:53:01,214 WARNING libqtile xcbq.py:set_property():L687 X error in SetProperty (wid=41943042, prop='WM_STATE'), ignoring
2020-05-17 12:15:38,082 WARNING libqtile xcbq.py:set_property():L687 X error in SetProperty (wid=41943042, prop='WM_STATE'), ignoring
```

# Configuration

link to my config:

https://github.com/T-Doc/tdots/blob/master/.config/qtile/config.py

If there is any more info you need, just ask.

Cheers

**Comment by tych0** [comment] 2020-05-17 14:25
On Sun, May 17, 2020 at 03:30:09AM -0700, Tommy Breslein wrote:
> # Issue description
> 
> When moving the mouse from one screen (i.e. monitor) to another, sometimes the focus changes, even though `follow_mouse_focus` is turned off. The expected behaviour would obviously be that the focus does not change at all. What is really weird is the "sometimes" bit - I would say it's about 50/50 whether the focus changes or not. Sometimes the focus changes 'backwards', as in the window my mouse just LEFT gains focus. Here are the possibly relevant options:
> 
> ```
> follow_mouse_focus = False
> bring_front_click = False
> cursor_warp = False
> focus_on_window_activation = "smart"
> ```

I've not seen this before, but I also use `focus_on_window_activation
= 'never'`. I assume that's whats going wrong here, can you see if
those windows are making focus requests via xtrace or similar?

**Comment by m-col** [comment] 2020-05-17 15:10
I'm seeing the same issue I think. The left-of-centre window is clicked at the start of the gif then it's just mouse movements. The far right window was last focussed of the right hand screen. The first mouse movement to the RHS doesn't do anything, then when the mouse goes back to the LHS it focusses the window on the right screen. Then I can consistently move mouse between screens and it always focusses the screen I moved away from. Pretty weird.
![Peek 2020-05-17 16-07](https://user-images.githubusercontent.com/44536113/82152380-46bfc500-9850-11ea-913c-de6a9efd7a90.gif)

**Comment by tych0** [comment] 2020-05-17 15:17
Huh, do you have follow_mouse_focus = True? It looks like there is a slight oddity with that code...

**Comment by m-col** [comment] 2020-05-17 15:25
I have it as False

**Comment by tych0** [comment] 2020-05-17 15:29
Wild, we should basically never be switching focus automatically if that's false.

I see you have the borders though. Do those count as the root window or the terminal window? I could imagine something with `enter_event()` miscalculating if it's the root window.

**Comment by m-col** [comment] 2020-05-17 15:46
That would have been interesting, but it happens when I use the master branch with normal borders.

This is the debug output when the focus changes, which happens as the mouse leaves the second window that it never clicked on:

> 2020-05-17 16:41:39,876 DEBUG libqtile xcore.py:_xpoll():L244 EnterNotify
> 2020-05-17 16:41:39,876 DEBUG libqtile xcore.py:_xpoll():L247 Handling: EnterNotify
> 2020-05-17 16:41:39,876 DEBUG libqtile hook.py:fire():L353 Internal event: client_mouse_enter((Window('vim [1] ~/.config/qtile/config.py'),), {})
> 2020-05-17 16:41:39,877 DEBUG libqtile xcore.py:_xpoll():L247 Handling: EnterNotify
> 2020-05-17 16:41:39,913 DEBUG libqtile xcore.py:_xpoll():L244 EnterNotify
> 2020-05-17 16:41:39,913 DEBUG libqtile xcore.py:_xpoll():L247 Handling: EnterNotify
> 2020-05-17 16:41:39,914 DEBUG libqtile hook.py:fire():L353 Internal event: current_screen_change((), {})
> 2020-05-17 16:41:39,914 DEBUG libqtile hook.py:fire():L353 Internal event: setgroup((), {})
> 2020-05-17 16:41:39,923 DEBUG libqtile hook.py:fire():L353 Internal event: focus_change((), {})

I don't have anything running on those hooks so they are a result of the change rather than the cause (I think). Could it be an EnterNotify on the root window?

**Comment by tych0** [comment] 2020-05-17 15:57
Yeah, that was my thought. Maybe we should print more info in handle_EnterNotify and see?

**Comment by m-col** [comment] 2020-05-17 16:15
This is `self.window.__dict__` being printed in the window's handle_EnterNotify and `event.__dict__` printed from the core's `enter_event` when the mouse moves from within the window to over it's border, :

> 2020-05-17 17:09:58,124 WARNING libqtile window.py:handle_EnterNotify():L1115 {'conn': <libqtile.backend.x11.xcbq.Connection object at 0x7f20a48e0f70>, 'wid': 23068694} ('xterm', 'XTerm')
> 2020-05-17 17:09:58,125 WARNING libqtile manager.py:enter_event():L692 {'response_type': 7, 'sequence': 8360, 'detail': 2, 'time': 21876277, 'root': 1490, 'event': 23068694, 'child': 0, 'root_x': 1963, 'root_y': 453, 'event_x': -1, 'event_y': 331, 'state': 0, 'mode': 0, 'same_screen_focus': 2, 'bufsize': 32}

And then when moving from the border to the root window we get this enter event, but no EnterNotify:
> 2020-05-17 17:10:05,845 WARNING libqtile manager.py:enter_event():L692 {'response_type': 7, 'sequence': 8424, 'detail': 2, 'time': 21883999, 'root': 1490, 'event': 1490, 'child': 0, 'root_x': 1957, 'root_y': 455, 'event_x': 1957, 'event_y': 455, 'state': 0, 'mode': 0, 'same_screen_focus': 2, 'bufsize': 32}

The second bit is when the focus change takes place.

**Comment by ramnes** [comment] 2020-09-14 09:17
#1907 got merged

**Closed by ramnes** 2020-09-14 09:17 UTC
