### ISSUE TITLE
Addind a ScratchPad causes floats_kept_above to break

### ISSUE THREAD

**Issue by ndunsworth** [qtile/qtile#4554] opened 2023-10-28 01:23 UTC
### Issue description

Just started using QTile today and when I added a single `ScratchPad` to my `config.py: groups` it broke floating windows and the config setting `floats_keep_above`.

I noticed this because the text editor I was using to edit my `config.py` file has a dialog window for "Find".  The "Find" window would start disappearing behind the text editor. 

The moment I disabled my single `ScratchPad` `config.py: groups` item it fixed the issue.  The text editors "Find" dialog no longer disappears behind windows.

I ran xprops on the text editor when this issue was happening and somewhere/somehow the main applications window is getting toggled to `_NET_WM_STATE_ABOVE`.

Tried various settings for `config.py: bring_front_click` without any resolution either.

### Version

0.23.0

### Backend

X11 (default)

### Config

```python
groups = [
    ScratchPad(
        'scratchpad',
        [
            DropDown(
                'fsystem',
                'caja',
                width=0.6,
                height=0.6,
                x=0.225,
                y=0.225,
                opacity=1
            ),
            DropDown(
                'terminal',
                'kitty',
                width=0.6,
                height=0.6,
                x=0.225,
                y=0.225,
                opacity=1
            ),
            DropDown(
                'editor',
                'xed',
                width=0.6,
                height=0.6,
                x=0.225,
                y=0.225,
                opacity=1
            ),
        ]
    )
]
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment] 2023-10-28 04:58
Are you able to check if #4417 fixes this?

The issue here that qtile treats scratchpads as a special case for layering and puts them at the top of the stack. A normal "kept_above" window has a lower stacking priority.

**Comment by ndunsworth** [comment] 2023-10-28 05:05
I can give that a shot.

The problem I was having though is that a normal app, not one in a 'ScratchPad', was having its floating windows broken.

I.E just having a 'ScratchPad' added to my 'groups' var causes all floating windows to break regardless of if I even trigger a 'ScratchPad' item to show.

I understand that a visible 'ScratchPad' would put it at the top of the WM stack.

**Comment by elParaguayo** [comment] 2023-10-28 05:06
Ok. I misunderstood. Still, please have a look at that PR as it does make some changes. I'll also see if I can recreate your issue.

**Comment by ndunsworth** [comment] 2023-10-28 05:35
Just updated to head and #4417 seems to have fixed it however I now have a question.

If I float a window and then use `lazy.window.toggle_floating()` I'm seeing with `xprops` that `_NET_WM_STATE_ABOVE` flag is still set.  Is that correct behavior?

That would mean that an accidental float of a window and then undo using `lazy.window.toggle_floating()` would leave the `_NET_WM_STATE_ABOVE` flag set.  Thus any current or future dialog's from the window or other applications can now be pushed behind when the window accidentally floated gets focus.

**Comment by jwijenbergh** [comment] 2023-10-29 20:15
#4417 is merged so this can be closed. Regarding your question it might be a bug but @elParaguayo might know more about this

**Closed by jwijenbergh** 2023-10-29 20:15 UTC
Labels: status: unconfirmed

**Comment by elParaguayo** [comment] 2023-10-29 20:25
It's a good question. My sense is we probably should remove the kept above flag. The problem is we can't differentiate between windows where it was added automatically (eg by the app or by our floats_kept_above setting) and where it was set by a user. I'm not sure if that matters...
