### ISSUE TITLE
simple_key_binder doesn't work after using a KeyChord

### ISSUE THREAD

**Issue by Koljasha** [qtile/qtile#4024] opened 2022-11-26 14:43 UTC
### The issue:

Qtile 0.22.1, in logs no errors or warns.
simple_key_binder doesn't work after using a KeyChord.
If I use simple_key_binder to generate Group switching keys, then Group switching does not work after using KeyChord. I am forced to do reload_config.
For the solution, I had to use: for i in Groups.
I see: https://github.com/qtile/qtile/issues/3734
My full config (correct) and line: https://github.com/Koljasha/archlinux/blob/7bef1b8d4d4fc972cdcbfa90453b5967ff739227/config/qtile/config.py#L279
For error: uncomment L279, comment L281-L290

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by helcone** [comment] 2022-12-08 20:43
I had the same issue, and I did the same as you. I did not report it because I was in a hurry in that moment and I just forgot but now that I try to reuse the functionality I have to go through again into troubleshoot, al;so I found some other posts with the same problem on the internet. https://www.reddit.com/r/qtile/comments/r2nwmg/comment/hm5xqsd/  and https://www.reddit.com/r/qtile/comments/sip7wz/comment/hvacq2g/ and this https://codesti.com/issue/qtile/qtile/3734

**Comment by elParaguayo** [comment] 2022-12-10 18:57
OK, pretty sure I know what the issue is here. Easy enough to fix but would be great if you or @kelvinvj111 could test once I've pushed a fix.

**Comment by Koljasha** [comment] 2022-12-10 21:33
I test version 0.22.2.dev74+gb8c2d132 not work (

**Comment by elParaguayo** [comment] 2022-12-10 21:35
It's not merged, you'd need to clone the repo and install that to test it.

**Comment by kelvinvj111** [comment] 2022-12-11 05:04
I checked out the pull request #4045 and installed that, however I wasn't able to switch workspaces at all. Found this error in qtile logs:
```
Traceback (most recent call last):
  File "/home/kelvin/.local/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/home/kelvin/.local/lib/python3.10/site-packages/libqtile/dgroups.py", line 141, in <lambda>
    libqtile.hook.subscribe.setgroup(lambda: self.key_binder(self))
  File "/home/kelvin/.local/lib/python3.10/site-packages/libqtile/dgroups.py", line 44, in func
    dgroup.config.keys.remove(key)
AttributeError: 'DGroups' object has no attribute 'config'
```
The pull request added this line: `dgroup.config.keys.remove(key)` at line 44, I changed it to `dgroup.qtile.config.keys.remove(key)` instead and now simple_key_binder works for me after activating a KeyChord.

**Comment by elParaguayo** [comment] 2022-12-11 08:23
Yes, that was a typo by me (sorry about that). I've pushed that updated fix.

Thanks for confirming it works - I'll get this merged.

**Comment by Koljasha** [comment] 2022-12-11 08:34
@elParaguayo Yes... it is working correctly now. Thanks.

**Closed** 2022-12-11 09:00 UTC
Labels: unconfirmed
