### ISSUE TITLE
Treetab disappears on qtile restart

### ISSUE THREAD

**Issue by jrwrigh** [qtile/qtile#3063] opened 2021-11-30 15:04 UTC
When I have an active group using the `treetab` windowing mode and restart Qtile, the tabs column disappears (or more likely, isn't redrawn). If I switch to a different group and switch back, the column is drawn correctly

https://user-images.githubusercontent.com/20801821/144071895-23719b7a-1a3f-44c8-b3b7-053a782a0f1a.mp4

`qtile --version`: `0.18.1`

<details>
<summary>~/.local/share/qtile/qtile.log</summary>

```
2021-11-30 07:54:56,827 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2021-11-30 07:54:57,357 WARNING libqtile config.py:<module>():L27 Number of monitors: 2
2021-11-30 07:54:57,526 WARNING libqtile config.py:<module>():L28 Monitor resolutions:[(1920, 1280), (1920, 1080)]
```
</details>

_Unrelated note: I tried to use the new "issue form" thing on GitHub, but it just returns a HTTP 400 error when I tried to submit it_

**Comment by m-col** [comment] 2021-12-05 16:40
Oddly I can't reproduce, even on `0.18.1` with an otherwise default config. If you try it with a mostly default config, does the issue persist?

**Comment by jrwrigh** [comment] 2021-12-06 03:01
Hmmm. Haven't tested it yet, but it might be a compositor issue (picom). I'll test with and without when I get a chance.

**Comment by jrwrigh** [comment] 2021-12-06 16:27
Shockingly, it's not a picom issue.

I've also tried it with the default config (while uncommenting the `layout.TreeTab()` line), and still get the same behavior.

Worth noting I'm on Manjaro 21.2.0, with qtile installed through the "normal" channels (ie. not from the AUR). I've had this issue over multiple computers, but with the same installation (ie. I physically moved the boot drive from one machine to the other). Those computers were running AMD and Intel CPUs (and their integrated graphics) respectively, so I doubt it's a hardware issue.

**Comment by tim-kilian** [comment] 2021-12-23 19:28
I ran in that problem too. Setting the default layout to a group will cause, that the panel 'stays open'.

**Comment by m-col** [comment] 2021-12-23 23:04
I think I figured out it. Please could you test out https://github.com/qtile/qtile/pull/3133 and see if that fixes it for ya?

**Comment by tim-kilian** [comment] 2021-12-28 22:39
Tested it right now and can confirm, that it fixes the issue! 👍🏼

**Comment by m-col** [comment] 2021-12-28 22:40
Great, thanks for confirming! Merged the fix.

**Closed** 2021-12-28 22:39 UTC
