### ISSUE TITLE
Improve install documentation - Add widget dependencies

### ISSUE THREAD

**Issue by pingu1m** [qtile/qtile#1492] opened 2019-11-18 02:54 UTC
Hi, I'm a new qtile user. Unfortunately, I wasted few hours getting a config to work because I did not had the python3 psutil package. I know that it may seem obvious for regular users, but for me who is branch new it was not. I believe there might be other dependencies that is required for all the widgets to work. A list list with the specific package to install would be just fine. Thank you.

**Comment by whatacold** [comment] 2019-11-18 14:37
Welcome :)

A workaround currently would be to check out the log at `~/.local/share/qtile/qtile.log`, which may look like this:

    2019-11-16 10:43:06,651 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
    2019-11-16 10:43:06,652 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
    2019-11-16 10:43:06,653 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
    2019-11-16 10:43:06,655 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.net.Net', No module named 'psutil'
    2019-11-16 10:43:06,658 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.memory.Memory', No module named 'psutil'

**Comment by pawamoy** [comment] 2019-11-18 16:05
Hi, I think this issue can be closed as duplicate of #1398

**Comment by tych0** [comment] 2020-03-05 02:20
Yep, I'll go ahead and close it for now.

**Closed by tych0** 2020-03-05 02:20 UTC
