### ISSUE TITLE
qtile crash after archlinux upgrade

### ISSUE THREAD

**Issue by zhiwenzheng** [qtile/qtile#2819] opened 2021-09-25 12:38 UTC
## I copied these log without a window manager
touch me: qtile start
Exception in callback Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:804
handle: <Handle Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:804>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 805, in f
    func(*args)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 497, in timer_setup
    update_interval = self.tick()
  File "/usr/lib/python3.9/site-packages/libqtile/widget/clock.py", line 73, in tick
    self.update(self.poll())
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 468, in update
    old_width = self.layout.width
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
Exception in callback Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:804
handle: <Handle Qtile.call_soon.<locals>.f() at /usr/lib/python3.9/site-packages/libqtile/core/manager.py:804>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 805, in f
    func(*args)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 454, in _actual_draw
    self._resize(self.length, self.widgets)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 323, in _resize
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 323, in <listcomp>
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/usr/lib/python3.9/site-packages/libqtile/configurable.py", line 51, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: GroupBox has no attribute: length
2021-09-25 20:28:52,470 libqtile start.py:start():L91  Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 210, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 231, in async_loop
    self._configure()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 184, in _configure
    self.core.scan()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 253, in scan
    win = window.Window(item, self.qtile)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1244, in __init__
    group.add(self)
  File "/usr/lib/python3.9/site-packages/libqtile/group.py", line 243, in add
    elif self.floating_layout.match(win):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'

**Comment by elParaguayo** [comment] 2021-09-25 12:41
Please search issues before posting.

Duplicate of: #2799, #2804, #2807 and #2817.

**Closed by elParaguayo** 2021-09-25 12:41 UTC
