### ISSUE TITLE
manager.py: UnicodeDecodeError Clipboard

### ISSUE THREAD

**Issue by llybin** [qtile/qtile#737] opened 2015-08-08 13:33 UTC
2015-08-08 20:31:51,781 ERROR _xpoll:753 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 730, in _xpoll
    r = h(e)
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 866, in handle_PropertyNotify
    value = prop and prop.value.to_utf8() or six.u("")
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 443, in to_utf8
    return six.b('').join(self).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 15: invalid continuation byte

Steps to reproduce:
echo 'author = "R�man Joost"' ; sleep 10

**Comment by llybin** [comment] 2015-08-08 17:37
I checked. The bug is produced in the [terminology](https://www.enlightenment.org/about-terminology) Maybe some other software..

**Comment by flacjacket** [comment] 2015-08-08 17:40
Thanks for the info, I'll see if I can't reproduce this tonight.

**Comment by flacjacket** [comment] 2015-08-09 15:07
So I'm not quite sure how to reproduce this. First, I don't think I can copy your line into a terminal correctly, because it is not a proper character. Are you able to get the output of something like:
```
>>> 'echo \'author = "R�man Joost"\' ; sleep 10'.encode()
```
to figure out what that character is?

Also, it's odd that it is tripping where it did, since that for handling the selection, i.e. copy/paste, do you know if terminology automatically sends a selection property with the output?

**Comment by llybin** [comment] 2015-08-09 15:33
You're right, source here: http://git.tuxfamily.org/pythonwifi/pythonwifi.git/tree/setup.py
I don't know about terminology.
How to reproduce:
1. install terminology
2. execute in terminology: cd /tmp; wget http://git.tuxfamily.org/pythonwifi/pythonwifi.git/plain/setup.py; cat /tmp/setup.py
3. copy the line in terminal and paste to the command: echo \'author = "R�man Joost"\' ; sleep 10

**Comment by llybin** [comment] 2015-08-09 16:33
right side terminology %)
![scr](https://sc-cdn.scaleengine.net/i/9f34b94eb2992027d7b32d3603aa21c9.png)

**Comment by m-col** [comment] 2021-01-09 18:36
I think this is a bug in terminology. What I did to come to this conclusion:

1. Open http://git.tuxfamily.org/pythonwifi/pythonwifi.git/plain/setup.py in firefox and copy the `author` line with the offending character ("ó")*
2. Pasting it into terminology, urxvt and firefox works fine
4. Copy the character from urxvt
5. Pasting it into urxvt and firefox works, but pasting into terminology gives me a "?" symbol.
6. Copy the character from terminology
7. Pasting it into terminology, urxvt and firefox works fine

However....I cannot reproduce the stack trace, so if that is still happening then I'm not sure how to reproduce.

Anyway since this is over 5 years old I'll close it for now. If this is still an issue, please feel free to re-open.

**Closed by m-col** 2021-01-09 18:36 UTC
Labels: bug
