### ISSUE TITLE
Using the InteractiveCommandClient API for restarting qtile

### ISSUE THREAD

**Issue by HeroGreen** [qtile/qtile#1882] opened 2020-08-23 18:52 UTC
# Issue description

When using the ```InteractiveCommandClient``` class from the ```libqtile.command_client``` package to restart a running instance of qtile like so 
```python
from libqtile.command_client import InteractiveCommandClient
c = InteractiveCommandClient()
c.restart()
```
an ```AssertionError``` is raised. While executing this from a python shell this is not a major issue as the feature of actually restarting qtile is completely functional. 
In contrast when trying to use to command API from a script (like from a continuously running while loop) it is quite inconvenient to check the ```AssertionError``` whenever calling the API to restart.

The stack trace indicates that restarting the qtile instance closes the socket before the command is sufficiently processed. I suspect this also applies to other command clients, although i haven't tested it. 

I feel like raising an error whenever the restart is invoked through the API is undefined behaviour and leads to code breaking in confusing ways.

# Qtile version

Newest release 0.16.1

# Stack traces

```
>>> c.restart()
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 89, in unpack
    assert len(data) >= HDRLEN
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/libqtile/command_client.py", line 184, in __call__
    return self._command.execute(self._current_node, args, kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/command_interface.py", line 230, in execute
    status, result = self._client.send((
  File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 135, in send
    return self.loop.run_until_complete(self.async_send(msg))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 166, in async_send
    data, _ = _IPC.unpack(read_data, is_json=self.is_json)
  File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 94, in unpack
    raise IPCError(
libqtile.ipc.IPCError: error reading reply! (probably the socket was disconnected)
```

# Configuration

Not sure if the configuration is actually relevant. I am happy to provide it if necessary.

**Comment by ramnes** [comment] 2020-08-26 07:53
Duplicate of #1355. :)

**Closed by ramnes** 2020-08-26 07:53 UTC
