### ISSUE TITLE
Nvidia drivers cause lag / slowdown when resizing or dragging windows

### ISSUE THREAD

**Issue by Dolvur** [qtile/qtile#4119] opened 2023-01-16 22:25 UTC
### The issue:

I am using EndeavourOS's community Qtile config and have only changed some keybindings currently, but I had the same issue on Fedora with another config, so I am pretty sure this is an issue with either Qtile or the nvidia drivers / how I installed the drivers.

Qtile version: ``0.22.1``

So far I tried installing the nvidia drivers in two different ways:
1) ``pacman -S nvidia nvidia-utils nvidia-settings xorg-server-devel opencl-nvidia``
2) From [Lutris recommendation](https://github.com/lutris/docs/blob/master/InstallingDrivers.md) for Arch: ``sudo pacman -S --needed nvidia-dkms nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader``

The issue is **highly** pronounced when for example watching a video on the second monitor (with mpv) or having discord open. Disabling hardware acceleration on discord removes the issue with discord.

Video example with nvidia drivers:
https://youtu.be/4nPN730OHIg

Example with nouveau drivers:
https://youtu.be/eGI8tQhGBDQ

I would be fine with using nouveau drivers except that high refresh rate does not seem to be working as smoothly.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by gabor-motko** [comment] 2023-01-16 22:54
That issue is fixed by #4091, but it's not included in 22.1. You can mitigate the issue by setting your mouse's polling rate to a lower frequency; 125 Hz worked perfectly for me.

**Comment by Dolvur** [comment] 2023-01-17 01:09
> That issue is fixed by #4091, but it's not included in 22.1. You can mitigate the issue by setting your mouse's polling rate to a lower frequency; 125 Hz worked perfectly for me.

Thanks for the help! Sadly it only fixed a small part of the problem though. I didn't manage to decrease the polling rate of my g305, but I upgraded to the latest qtile ``0.22.2.dev115+g653c52c2`` with the git AUR. Moving a floating window is now very snappy **except** when I run a video with mpv (guessing it is because of some hardware acceleration stuff, but I am not sure). 

The resizing still seems laggy and I also got another bug during the recording where the tiling broke a little, which might be unrelated since I am not using the release version.

https://youtu.be/LSQFDdl3CuU

**Comment by Jareng** [comment] 2023-01-17 09:03
You can try to disable picom if it's enabled and/or disable composition pipeline in nvidia-settings

**Comment by Dolvur** [comment] 2023-01-17 10:51
> You can try to disable picom if it's enabled and/or disable composition pipeline in nvidia-settings

Unfortunately I did not notice any difference with or without picom, and composition pipleline was already disabled. I tried enabling it and full composition pipeline but I didn't notice any difference.

However, I did notice that when using another terminal over alacritty like xfce, I did not notice any slowdown when resizing the windows or dragging the windows with an video playing on my second monitor with mpv. Dragging the windows was also fast and snappy except if I drag the windows over the video, then the slowdown occurs.

This makes me believe even more that the problem somehow lies with applications using hardware acceleration. Alacritty is GPU accelerated so it would make sense that it is the reason why it performs worse

**Comment by Dolvur** [comment] 2023-01-18 16:53
I am switching to i3 for the moment, so I am closing this issue. If anyone else get this issue, I can reopen it.

**Comment by jwijenbergh** [comment] 2023-01-24 23:08
I will look into this, maybe there's still something we can do in qtile.

**Comment by Dolvur** [comment] 2023-01-25 00:28
I installed qtile git version `0.22.2.dev121+g46ff94d` now and tested around a little bit with the default config. I still have the issue, but if I disable my second monitor everything is smooth as butter! Also if I now decrease my refresh rate from 144hz down to 60hz the issue appears again (even though I am only using one monitor).

I don't know how to set the x11 drag polling rate variable, unfortunately. I did some quick googling but didn't manage to find out how. I tried adding like x11_drag_polling = 60 to to /etc/X11/xorg.config but didn't manage to boot into the graphics then so I removed it. I am still quite new to a lot of stuff in linux so I am not well versed in for example X11 and how you configure it.

I found a reddit thread [extreme_lag_while_dragging_a_window_if_any_video](https://www.reddit.com/r/gnome/comments/tzdw0d/extreme_lag_while_dragging_a_window_if_any_video/) where people seem to be having the same problem. However, they were using gnome (seemed to be related to mutter), so perhaps this is not related to qtile. The strange thing is that i3 works fine for me. I haven't dug into that thread a lot since I don't have much free time currently, but it does seem to contain a lot of interesting information.

I tried decreasing my mouse polling rate to 125hz and the issue decreased dramatically, however there were stutters when resizing or moving the window quickly. When I disabled my second monitor, everything became buttery smooth like before.

Sadly, I am quite busy right now, so I probably won't be able to test or reply as much as I would've wanted.

**Comment by elParaguayo** [comment] 2023-01-25 16:42
You would add `x11_drag_polling_rate = 60` to your qtile config file, not the xorg config.

**Comment by Dolvur** [comment] 2023-01-25 17:27
I tried messing around a bit with it, but still had the issue. My initial impressions were that the windows were sort of lagging and teleporting behind my cursor rather than slowly dragging behind and that the computer didn't slowdown as much during the lag. But after some more testing I am unsure if it actually affects the issue or not. I tried with lower numbers like 20 but didn't feel like I noticed a difference

**Comment by jwijenbergh** [comment] 2023-01-28 12:50
This definitely sounds like an nvidia driver bug, but nonetheless it might be something we can handle. For example i3 starts their own event loop for just drag events which is maybe why it behaves differently (better). 

Are you changing the x11_drag_polling rate for each screen in your config?

**Comment by jwijenbergh** [comment] 2023-01-28 12:54
Also bspwm seems to have this issue https://github.com/baskerville/bspwm/issues/1261

**Comment by jwijenbergh** [comment] 2023-01-28 13:41
@Dolvur do you have the ability to test the #4141 pull request? Note that x11_drag_polling_rate is now removed

**Comment by Dolvur** [comment] 2023-01-30 10:23
I tested that branch (qtile version `0.18.1.dev659+gb796bce7`) and the issue is almost completely gone! With both monitors active, it is butter smooth 144hz on my main monitor and 60hz on my secondary monitor when dragging around the window with no lag or drag behind.

When I have a video stream open with mpv, I noticed that it now seems to be 60hz when dragging around a window on both screens (disabling second monitor makes it smooth again). However, this also seems to be the case in i3 and I am pretty sure Windows does this as well but I am not certain. The only other small thing I noticed is a little hiccup when moving the window between the monitors where there is a small initial stutter.

Other than that, it works perfectly. Those issues are also rather small compared to before and most people will probably not notice unless they specifically look for it.

**Comment by jwijenbergh** [comment] 2023-01-30 17:43
> qtile version 0.18.1.dev659+gb796bce7

Weird version number though, but I assume you're on the correct branch.

> I noticed that it seems to be 60hz when dragging around a window on both screens 

I think this is a X11 limitation, don't quote me on this though

> The only other small thing I noticed is a little hiccup when moving the window between the monitors where there is a small initial stutter.

Hmmm, does this specific hiccup also happen on i3?

> Other than that, it works perfectly. Those issues are also rather small compared to before and most people will probably not notice unless they specifically look for it.

Good that it works well for you. If this fix also works for other people I will merge it

**Comment by Dolvur** [comment] 2023-01-31 14:33
No problem! Yeah, I cloned the repo switched to nvidia-resize and used `pip install .`. Idk why the version number seems so old but it is what it gives me.

Also the small hiccup problem does not happen on i3. I only get the issue when I am streaming video into mpv by using streamlink. If I am watching twitch on e.g. firefox I have no issues and dragging the window is a smooth 144hz, even if I drag it between the screens (60hz on the second). And if I watch a local video on my computer using mpv I have no issues either.

I just tried with discord and I get the small hiccup with it as well. As long as it is open and I move any window across there usually is a small hiccup. I tried disabling hardware acceleration on discord and and the issue disappeared

**Comment by jwijenbergh** [comment] 2023-01-31 20:48
It would be great if we could get that small hiccup issue fixed. Just a thought, does it also happen with `follow_mouse_focus` set to `False`? https://github.com/qtile/qtile/blob/ffbf518ed7b2f376b77347fae09aa92514e89d4a/libqtile/resources/default_config.py#L163

I am trying to find a way to reproduce it, but so far have been not so lucky on my system. My thought is that maybe we do something wrong with focus behaviour.

> i3 also have laggy resizing on any window when either mpv stream or discord is open

God I hate x11 :laughing: 

> Like I mentioned before, the issues are very minor now and just a small annoyance.

That's great!

>  I am fine with closing this thread now unless you want to look into the hiccup issue

I will do some more testing, if I find that this is unfixable I will close it but it's possible that we're doing something wrong.

Thanks.

**Comment by Dolvur** [comment] 2023-02-01 12:15
I tried with it set to false and still have issues. However I noticed two things. One, I am not using bare-bones qtile and when I killed picom the hiccup issue was gone. Secondly, when I drag a window I notice that the mpv window gets focused a short duration (flickers brighter blue) even though it should keep focusing the window I drag. And this matches when it lags while picom is running. If I disable picom I get no hiccup but it still focuses for a short while.

So the issue seems to be a combination of qtile wrongly focusing the wrong window while I drag for a short while combined with picom

**Comment by jwijenbergh** [comment] 2023-02-18 18:36
Sorry for the radio silence...

I am happy to merge #4141 so that at least a large part of your issues are fixed. I have not yet managed to fix the remaining issue you're having with the 'stutter'. 

I still need some confirmation from users that #4141 is a good way to fix it though...

**Comment by jwijenbergh** [comment] 2023-02-18 19:31
> > That issue is fixed by #4091, but it's not included in 22.1. You can mitigate the issue by setting your mouse's polling rate to a lower frequency; 125 Hz worked perfectly for me.
> 
> Thanks for the help! Sadly it only fixed a small part of the problem though. I didn't manage to decrease the polling rate of my g305, but I upgraded to the latest qtile `0.22.2.dev115+g653c52c2` with the git AUR. Moving a floating window is now very snappy **except** when I run a video with mpv (guessing it is because of some hardware acceleration stuff, but I am not sure).
> 
> The resizing still seems laggy and I also got another bug during the recording where the tiling broke a little, which might be unrelated since I am not using the release version.
> 
> https://youtu.be/LSQFDdl3CuU

That tiling breakage should be fixed with #4164

**Comment by Maxga** [comment] 2023-04-22 07:44
With the fix, I can move e.g. terminals just fine on x11_polling_rate 120, however moving e.g. steam windows is still painfully slow.

**Comment by jwijenbergh** [comment] 2023-04-22 09:33
> With the fix, I can move e.g. terminals just fine on x11_polling_rate 120, however moving e.g. steam windows is still painfully slow.

What about #4141? Or making the polling rate 60?

**Comment by jwijenbergh** [comment] 2023-05-29 13:43
Would be great if you can test this

> > With the fix, I can move e.g. terminals just fine on x11_polling_rate 120, however moving e.g. steam windows is still painfully slow.
> 
> What about #4141? Or making the polling rate 60?

@Dolvur, no worries if you don't have the time. Am currently just cleaning issues

**Comment by crillon** [comment] 2023-06-22 10:46
@jwijenbergh Hi, I'm faced with the same issue. But after applying #4141, everything works nicely and smoothly, thank you

**Comment by Dolvur** [comment] 2023-06-24 23:14
> @Dolvur, no worries if you don't have the time. Am currently just cleaning issues

Sorry, I haven't been very active recently. I don't have the same setup as before so I can unfortunately not test anything right now. I do remember that with #4141 everything worked really well and smooth as it seemed to have done for @crillon so I do think you should be able to merge it without any problems.

@crillon Did you notice any of the small stutters that I mentioned before (https://github.com/qtile/qtile/issues/4119#issuecomment-1408358299) when dragging (hardware accelerated?) windows between two monitors?

**Comment by crillon** [comment] 2023-06-25 12:39
@Dolvur No, I don't have any issues dragging the window between monitors. But both of my monitors are 60HZ, maybe that's the reason

**Comment by jwijenbergh** [comment] 2023-07-09 17:33
https://github.com/qtile/qtile/pull/4141 is merged, should now be fixed.

@Dolvur Could you make a new issue for the dragging between monitors + test default config?

**Closed by jwijenbergh** 2023-07-09 17:33 UTC
Labels: unconfirmed

**Comment by jwijenbergh** [comment] 2023-07-10 21:31
Thanks @Dolvur. Take your time, hopefully we can make everything smooth!
