### ISSUE TITLE
Systray widget crash

### ISSUE THREAD

**Issue by ArchKubi** [qtile/qtile#3260] opened 2022-01-27 06:52 UTC
2022-01-27 09:48:40,366 ERROR libqtile bar.py:_configure_widget():L324 Systray widget crashed during _configure with error: ConfigError('Only one Systray can be used.')
[config.txt](https://github.com/qtile/qtile/files/7948239/config.txt)

**Comment by elParaguayo** [comment] 2022-01-27 07:08
Hmm. That shouldn't have happened.

Did this happen the first time you started or did you restart/reload the config before the crash happened?

**Comment by darkclip** [comment] 2022-01-27 09:24
confirm the issue.
multi-screen setup, only one systray init in config.
error on fresh start, when manually reload config, widget loads fine.

**Comment by elParaguayo** [comment] 2022-01-27 09:25
Ah. I wonder if it's crashing because of screens being reconfigured.

Will test.

**Comment by elParaguayo** [comment] 2022-01-27 10:14
Confirmed - it's `cmd_reconfigure_screens`.

Sorry about that.

Will work on a fix.

**Comment by darkclip** [comment] 2022-01-27 11:00
wow, that was fast, you guys good work!

**Comment by elParaguayo** [comment] 2022-01-27 11:01
> wow, that was fast, you guys good work!

I try to be quick when it's a bug that I created!

Won't always be this quick...

**Comment by darkclip** [comment] 2022-01-27 11:19
tested your patch, it works when systary is used by itself, however i use it inside of a widgetbox, so it still crashes... @elParaguayo

**Comment by elParaguayo** [comment] 2022-01-27 11:22
Ha. WidgetBox was one of mine too... On it!

**Comment by m-col** [comment] 2022-01-27 11:29
@elParaguayo I think `manager.c.reconfigure_screens()` should work in the tests, as it doesn't require the output configuration to change, and it'll just do its thing anyway. So perhaps work testing systray within and without widgetbox, one vs two screens, reconfigure_screens, reload_config?

**Comment by elParaguayo** [comment] 2022-01-27 11:35
Yeah. Was thinking we need a test.

`WidgetBox` is an interesting case because, if the box is open, then the widgets are in the bar and configured there. If it's closed, then the configuring inside the box so we need to cover both cases.

This will take a little longer (and I should do my job too...)

**Comment by darkclip** [comment] 2022-01-27 12:50
no worries,  good thing about python is that i can get myself all kinds of workaround until it officially gets fixed.

**Comment by elParaguayo** [comment] 2022-01-27 14:02
@darkclip - are you able to test #3262?

**Comment by darkclip** [comment] 2022-01-27 16:14
@elParaguayo #3262 works for me!

**Comment by ArchKubi** [comment] 2022-01-27 20:23
no ı use 1 monitor ı start qtile start 
widget crashes : systray (click to hide) and ı refresh qtile this fix but every time qtile start systray crash

**Comment by elParaguayo** [comment] 2022-01-27 20:48
I can't see any reason for that to crash unless `cmd_reconfigure_screens` is being triggered when you start qtile for some reason.

Are you able to these the PR to see if it solves your issue?

**Comment by ArchKubi** [comment] 2022-01-28 02:07
ı forget what is PR ?

**Comment by darkclip** [comment] 2022-01-28 06:41
@ArchKubi PR means pull request, which I think for you is #3261

**Comment by elParaguayo** [comment] 2022-01-28 06:58
Well, it's also been merged now so you could try installing the git version to see if this is fixed for you.

I'll close for now but @ArchKubi if you still have this bug once you've installed the updated (either by using the git version or by waiting for the next release) then please re-open the issue.

**Closed by elParaguayo** 2022-01-28 06:58 UTC
Labels: bug, widgets

**Comment by ArchKubi** [comment] 2022-01-28 07:07
okay ı wait new release
