### ISSUE TITLE
Firefox right click menu disappears 

### ISSUE THREAD

**Issue by parasbhanot** [qtile/qtile#2479] opened 2021-05-21 12:29 UTC
##### Os - Arch

hello everyone , 

I am facing weird issue with firefox based browsers. 

when i right click on any page in firefox then menu suddenly disappears and first item in right click menu is automatically selected which is annoying . i am also facing this issue in ilbrewolf which is also a firefox based browser. 

This is problem is not found if  tree  or max  layout is selected but other layouts like  monadtall , monadwide, ratiotile , tile etc show same behaviour . 

Am i doing something wrong ?

**Comment by elParaguayo** [comment] 2021-05-21 14:59
This looks like a duplicate of #2460

**Comment by ramnes** [comment] 2021-05-21 15:10
Definitely. I'm closing in favor of the other one, let's keep it in one thread. :)

**Closed by ramnes** 2021-05-21 15:10 UTC
