### ISSUE TITLE
Changing a window to floating freezes it in some layouts

### ISSUE THREAD

**Issue by kynikos** [qtile/qtile#624] opened 2015-02-28 07:00 UTC
Open a new window in one of the following layouts:
- Max
- MonadTall
- TreeTab
- VerticalTile
- Zoomy

Then drag the window so that it floats: it will freeze; it will still be possible to type/click blindly, but it won't be refreshed until switching to another group and coming back.

**Comment by Etn40ff** [comment] 2016-05-16 16:12
I can confirm the same happening on qtile 0.10.5 with both columns and Max layouts.

**Comment by flacjacket** [comment] 2016-05-16 16:31
Does anything go into the log when this happens?

**Comment by Etn40ff** [comment] 2016-05-16 16:47
It does not look so. 
One other weird thing is that windows borders do not appear to change when starting to float. The border color/thickness will only be updated after switching group and returning back.

**Comment by flacjacket** [comment] 2016-05-16 16:54
I just realized there has been a big overhaul of floating behavior that didn't make it into 0.10.5, this may be fixed on develop, are you able to test this off the current git version? We are probably overdue for a release with those fixes.

**Comment by Etn40ff** [comment] 2016-05-16 16:55
I have the same issues on develop

**Comment by ramnes** [comment] 2018-11-15 20:41
I can't reproduce this, are you still affected by this bug? If so, what is the application freezing?

**Comment by Etn40ff** [comment] 2018-11-15 20:50
The bug is still there in 0.12.0. 

To reproduce: 

- go to a group with layout Max and open an xterm

- type something (works as espected)

- set the xterm to float (the windows is now frozen, or better it does not update its content any more but the app is ok)

- type some more (nothing happens)

- swithch to a different group then back 

- the window is now unfrozen and shows also the content typed while frozen

**Comment by ramnes** [comment] 2018-11-15 21:00
I just tried that and it works just as expected. :disappointed: 

Can you please provide a link to your configuration?

**Comment by ramnes** [comment] 2018-11-15 21:04
Are you using xcompmgr by any chance? (if so, I guess that it is juts a duplicate of #417)

**Comment by Etn40ff** [comment] 2018-11-15 21:10
here you go: https://pastebin.com/g4TmjLRR

**Comment by Etn40ff** [comment] 2018-11-15 21:12
I do use xcompmgr and I can confirm that the bug depends on it.
Please close this

**Comment by ramnes** [comment] 2018-11-15 21:20
Closing in favor of #417.

Thank you @Etn40ff!

**Closed by ramnes** 2018-11-15 21:20 UTC
Labels: bug, floating, unconfirmed
