### ISSUE TITLE
0.25.0: Five failing tests

### ISSUE THREAD

**Issue by dvzrv** [qtile/qtile#4762] opened 2024-04-13 08:30 UTC
### Issue description

Hi :wave: 

I'm currently upgrading the package on Arch Linux to 0.25.0 and ran into failing tests:

```
=========================== short test summary info ============================
FAILED test/backend/x11/test_window.py::test_urgent_hook_fire[wayland-2] - Ke...
FAILED test/widgets/test_clock.py::test_clock_datetime_timezone - AssertionEr...
FAILED test/widgets/test_clock.py::test_clock_pytz_timezone - AssertionError:...
FAILED test/widgets/test_clock.py::test_clock_dateutil_timezone - AssertionEr...
FAILED test/widgets/test_clock.py::test_clock_change_timezones - AssertionErr...
= 5 failed, 1726 passed, 71 skipped, 4 xpassed, 2 warnings in 1017.94s (0:16:57) =
```

[qtile-0.25.0-1-x86_64-check.log](https://github.com/qtile/qtile/files/14965804/qtile-0.25.0-1-x86_64-check.log)
[qtile-0.25.0-1-x86_64-build.log](https://github.com/qtile/qtile/files/14965805/qtile-0.25.0-1-x86_64-build.log)

In regards to how tests are run, nothing has been changed since last upgrade:
https://gitlab.archlinux.org/archlinux/packaging/packages/qtile/-/blob/c9582a5362b017c90a6f3c06b57003dd1326901b/PKGBUILD

### Version

0.25.0

### Backend

X11 (default), Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment] 2024-04-13 13:03
Hmm, first one looks a little strange to me, can you try the above PR and see if that fixes it? The rest all look like "the same" bug, I will take a look at those in a bit.

**Comment by elParaguayo** [comment] 2024-04-13 17:23
Fair enough. Let me take a look.

**Comment by tych0** [comment] 2024-04-13 17:31
The math looks like it is pretty clearly ignoring the timezone delta, but I really don't understand why that would happen.

**Comment by elParaguayo** [comment] 2024-04-13 18:04
If I run `pkgctl build --testing` to build this in a chroot, all those clock tests pass successfully for me.

**Comment by jwijenbergh** [comment] 2024-04-13 22:45
Fwiw the clock tests also fail for me on my machine

**Comment by jwijenbergh** [comment] 2024-04-14 11:39
tests worked for me before `13e9ac849d6625280837318bf6ade7939e3896f2`

**Comment by elParaguayo** [comment] 2024-04-14 11:41
Yes. There's no doubt that that's the cause bit y weird that it's passing for me and on CI.

Will take a look later.

**Comment by jwijenbergh** [comment] 2024-04-14 12:05
Give #4766 a shot

**Comment by elParaguayo** [comment] 2024-04-14 17:56
@jwijenbergh did the first test pass for you? That's not related to the `Clock` widget.

**Comment by jwijenbergh** [comment] 2024-04-14 18:05
Sorry GitHub auto closed this

**Comment by tych0** [comment] 2024-04-21 14:29
@dvzrv can you try #4775 ? I am pretty sure that will fix it.

**Comment by elParaguayo** [comment] 2024-05-04 13:03
I think these are all resolved now.

**Closed by elParaguayo** 2024-05-04 13:03 UTC
Labels: status: unconfirmed
