### ISSUE TITLE
Totally messed up fullscreen 

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#729] opened 2015-07-27 21:00 UTC
Sometimes I get the real fullscreen (i.e. in vlc), sometimes I still see my panels (i.e. in flash) and have to do `lazy.window.toggle_fullscreen()`. Fullscreen always should be "real" and cover all the space.

---

Also sometimes when entering fullscreen in flash, esc key or cursor keys doesn't work. You have to click to get focus and then it works. I am sorry, but I can't give an example now. Maybe someone can point it in comments.

---

And also when there is multiple windows in `Max` layout and one of them opens fullscreen (flash), fullscreen window doesnt even get the focus, so its under other windows.

Steps to reproduce:
1. Activate `Max` layout
2. Spawn some window
3. Spawn browser with youtube
4. Play video and click on fullscreen

Actual results:
Fullscreen window is somewhere below, because focus is returned to the different window. I believe that its related to #727, but I wanted to mention that even in relationship with the flash.

**Comment by kynikos** [comment] 2015-07-30 03:31
Another full screen issue can be seen for example when trying to exit full-screen mode in Firefox after pressing `F11`: pressing `Esc` or `F11` should return to the normal mode, but they don't work for me.

**Comment by kamilchm** [comment] 2015-07-30 05:38
I have the same issue with Firefox. Can't get back to normal mode from fullscreen.

**Comment by dequis** [comment] 2015-08-01 03:03
I think fullscreen has been like that for a long time, and i'm so used to it that i apply workarounds to it without even noticing.

In the case of firefox, I press my hotkey for `toggle_fullscreen` and *then* f11 to exit its fullscreen mode.

I probably use `toggle_fullscreen` all the damn time.

**Comment by jsqliu** [comment] 2015-08-03 04:38
I frequently put a F11 "fullscreen" firefox within a tile (and similarly for other programs).  It's nice when you don't want bars/tabs taking up space.

**Comment by kamilchm** [comment] 2015-08-12 14:38
I fixed firefox by change ``auto_fullscreen`` to ``False`` and using a hotkey for `toggle_fullscreen` for now.

**Comment by atommixz** [comment] 2015-09-17 14:05
I have same issue. I hate it!

**Comment by baccenfutter** [comment] 2015-12-21 12:44
I have the same issue and I hate it, too! Has no dev looked into this or is it not easy to fix?

**Comment by baccenfutter** [comment] 2015-12-21 12:52
Let me elaborate some more, hoping it helps fixing this:

It seems as if Qtile forces the window back into full-screen. I can clearly see how Firefox tries to go out of full-screen, but within a second it pops back into full-screen. I've tried `lazy.window.toggle_fullscreen()` and F11 in every possible combination from very fast to very slow - Firefox remains in full-screen, while window borders pop in to and out of full-screen, while trying.

The only way out of full-screen for me is to `kill -9 firefox` and restart firefox. That is a disappointing work-around, though.

**Comment by dequis** [comment] 2015-12-21 20:08
That commit improves things but as far as i know it's not a complete fix for all the fullscreen issues. And yes this is tricky to debug.

**Comment by emdete** [comment] 2015-12-22 23:21
my expectations about fullscreen is that however i enter fs the effect is the same, either initiated via qtile toggle_fullscreen or by the program (for example pressing f11). so qtile and the program must know about it (some programs, notable browsers change their layout on fullscreen).

these are the problems that i found:

 - if the program wants to leave fs qtile does not react on that (simple fix: remove line 288 in window.py)

 - if you change groups while a window is fs qtile gets screwed up badly sometimes

 - if qtile enters fs via toggle_fullscreen it does not tell the program about that state (so the broweser doesn not change layout)

 - it seems that some programs (for example geeqie) use totally different protocols to enter fs, it seems qtile doesn't even notive that.

i will dig further but if someone else has some hints please let me know - you can see my changes in my fork.

**Comment by flacjacket** [comment] 2016-01-07 03:34
Hopefully this is improved by the recent changes to fullscreen code, tho I can't guarantee it solves all the fullscreen problems.

**Comment by danmilon** [comment] 2016-05-23 16:15
When I fullscreen my media player, it loses focus and and keypresses go to the window in the back. Clicking the fullscreen window fixes this. This is strange behaviour to me. Is there a plan to fix this? If I were to try and fix this, where should I look?

**Comment by hgaiser** [comment] 2016-09-11 10:40
@danmilon I am experiencing the same when using the toggle_fullscreen() command on any window. The fullscreened window loses focus at that point and keypresses go to the window in the background.

**Comment by m-col** [comment] 2021-01-09 18:42
I am closing this because:

- I cannot reproduce
- there have been lots of focus changes in the past year, so it's probably fixed
- it's been over 4 years, so many other changes could have fixed it, causing my to not be able to reproduce it

Please feel free to re-open this if it is still an issue!

**Closed by m-col** 2021-01-09 18:42 UTC
Labels: bug, fullscreen

**Comment by odorT** [comment] 2021-08-30 14:22
I have the issue like the others have:

Assume that I opened application in full screen  mode(e.g. minecraft). in 1st group. Then I switched to 2nd. The problem starts when I want to go back to 1st group, I see 0.5s of the game, then nothing, just wallpaper. And the application is focused, because when I do modkey + w it closes. I am getting annoyed with this issue. If it has already been solved, or any walkaway exists. please tell me

**Comment by m-col** [comment] 2021-08-30 18:23
Hi @odorT, please could you open a new issue describing your problem including the qtile version you are using, any log output you see when the problem happens, and the relevant parts of your configuration that are needed for us to reproduce the error.
