### ISSUE TITLE
Quote characters are displayed wrong in website config example

### ISSUE THREAD

**Issue by merwok** [qtile/qtile#2702] opened 2021-08-16 14:47 UTC
# Issue description

On your website, if you expand the config example, you can see quoted strings displayed wrong:

```
                widget.Clock(format=&#x27;%Y-%m-%d %a %I:%M %p&#x27;),
```

```
floating_layout = layout.Floating(float_rules=[
    {&#x27;wmclass&#x27;: &#x27;confirm&#x27;},
```

**Comment by elParaguayo** [comment] 2021-08-16 14:53
Can you provide a link to a specific page?

**Comment by merwok** [comment] 2021-08-16 16:51
The example config (expanded) on the home page http://www.qtile.org/

**Comment by elParaguayo** [comment] 2021-08-16 17:50
Ah. That website. I thought you were referring to our docs.

Thanks - let me sort this.

**Comment by elParaguayo** [comment] 2021-08-28 09:18
@merwok - I'm going to close this, not because the issue is fixed but because I think the plan is to rethink the main website entirely.

**Closed by elParaguayo** 2021-08-28 09:18 UTC
