### ISSUE TITLE
Default configuration's bindings do not work after a configuration error

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#1411] opened 2019-08-29 03:15 UTC
How i restart Qtile with a config error? Mod+Ctrl+r Don't work for me. Thank you

**Comment by pawamoy** [comment] 2019-08-29 16:08
What is your mod key? Maybe it's not mapped correctly.

Can you open a terminal with Mod+Return? If yes, try to do this:

```sh
xev & sleep 5; pkill xev
```

...and hit your mod key to see what it outputs.

Then paste us the result, along with the output of `xmodmap` and any lines in your `~/.xprofile` that could change the keyboard mappings.

**Comment by przymusp** [comment] 2019-08-29 18:28
You can also use qtile-cmd 
```bash
qtile-cmd -o cmd restart
```

**Comment by pawamoy** [comment] 2019-08-29 19:24
You forgot `-f` ;)

```
qtile-cmd -o cmd -f restant
```

Typically ran in another TTY (hit control-alt-F2)

**Comment by cr1ogen** [comment] 2019-08-30 00:30
My Mod key is windows key, the command xev & sleep5; pkill xev give me this result .

KeyRelease event, serial 33, synthetic NO, window 0x1800001,
    root 0x1e4, subw 0x0, time 222242, (-68,8), root:(1680,72),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyPress event, serial 36, synthetic NO, window 0x1800001,
    root 0x1e4, subw 0x0, time 223058, (-68,8), root:(1680,72),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x1800001,
    root 0x1e4, subw 0x0, time 223218, (-68,8), root:(1680,72),
    state 0x40, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
[1]  + 2058 terminated  xev  .

My mod key works when the config is with no error. I compiled the last version

**Comment by pawamoy** [comment] 2019-08-30 10:59
Thank you, I have the same output so I think we can safely say your keyboard mappings are correct. 

And in fact, I'm experiencing the same issue: sometimes when I have a configuration error, keyboard keys are not working (mod+ctrl+r). Not one of them. It's like Qtile is frozen or something.

We should find a way to reproduce this.

**Comment by ramnes** [comment] 2019-08-30 16:44
Setting this as "unconfirmed" because I can't reproduce, but this is pretty concerning indeed.

**Comment by cr1ogen** [comment] 2019-08-31 00:43
Thank you!! i close this issue?

**Comment by ramnes** [comment] 2019-08-31 09:04
No, please keep it open. As @pawamoy stated, the goal here is to find a way to reproduce this problem reliably, so that we can start looking into it seriously.

**Comment by cr1ogen** [comment] 2019-09-02 19:39
Ok. Thank you

**Comment by montdor** [comment] 2019-09-13 22:20
Just to give some credence, this is also happening to me on configuration error. 

I tried every "mod key" I could think of, and it wont register. The only thing that works at all is moving between workspaces on the default bar by clicking them with the mouse

**Comment by pawamoy** [comment] 2019-09-13 23:21
I also noticed that when I don't define `keys` in a config file, the default ones are not loaded. I think it's related. It seems the default keys are never loaded, config error or not.

**Comment by lulivi** [comment] 2019-12-24 17:34
Hello, I'm having the same issue as @cr1ogen, just, no keybindings available when error in local config. I can interact with the bar changing groups and those things though.

**Comment by actbusy** [comment] 2019-12-26 16:49
Hi, 

I can get the bug by either
* passing non-existent config file e.g. `--config /dev/null`
* or purposely `raise Exception` in config file

That triggers `config = confreader.Config()` at https://github.com/qtile/qtile/blob/ee9e004a3642b9feb31d2ca981581675969cf1fd/libqtile/scripts/qtile.py#L108-L115

However the following suggests `config.keys` will be empty? https://github.com/qtile/qtile/blob/ee9e004a3642b9feb31d2ca981581675969cf1fd/libqtile/confreader.py#L64-L74

Because `self.keys = []  # type: List[config.Key]`, 

`getattr(self, "keys", default["keys"])` returns `[]`.

version: c03c1e2b2874918ef1fb8359bc2d5cb0eefc66b8

**Comment by Brn9hrd7** [comment] 2020-01-07 03:19
I was able to bisect this to commit [72f35e2c2128aed19571c6b7240988db34f58645](https://github.com/qtile/qtile/commit/72f35e2c2128aed19571c6b7240988db34f58645) (Re-enable Python 3.5 support), which also contains the line @actbusy mentioned.

Maybe the issue is related to the used Python version? This might be the reason why @ramnes couldn't reproduce it. I've seen this issue on both Arch(Python 3.8) and Ubuntu 19.10(Python 3.7). Unfortunately I wasn't able to install qtile with pip on Ubuntu 18.04(same issue as https://github.com/qtile/qtile/issues/1502) and the version in the repo is too old.

**Comment by tych0** [comment] 2020-03-04 02:04
I think the above PR probably fixes it, if anyone has time to test?

**Comment by Brn9hrd7** [comment] 2020-03-04 11:52
Just tested this PR, fixes the issue for me.

**Comment by tych0** [comment] 2020-03-07 16:17
Cool, I merged that, so I'll go ahead and close this now. Thanks all for the work on this!

**Closed by tych0** 2020-03-07 16:17 UTC
Labels: bug, unconfirmed
