### ISSUE TITLE
Update 0.22.1-1 on Arch break LightDM

### ISSUE THREAD

**Issue by sebastienPoussard** [qtile/qtile#3859] opened 2022-09-23 13:32 UTC
### The issue:

After the last update on Arch which is version `0.22.1-1`
LightDM could not start Qtile anymore, after entering password, LightDM is stuck in a loop.
Killing lightDM and using `qtile start` from TTY1 show the following errors : 
```
Traceback (most recent call last):
  File "/usr/bin/qtile", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 88, in start
    q = make_qtile(options)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 82, in __init__
    raise QtileError("No DISPLAY set")
libqtile.utils.QtileError: No DISPLAY set
```
I also tried with a different display manager (SLiM)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by sebastienPoussard** [comment] 2022-09-23 14:02
When downgrading all packages to yesterday, everything works properly
in /etc/pacman.conf : 
```
[core]
SigLevel = PackageRequired
Server=https://archive.archlinux.org/repos/2022/09/21/$repo/os/$arch

[extra]
SigLevel = PackageRequired
Server=https://archive.archlinux.org/repos/2022/09/21/$repo/os/$arch

[community]
SigLevel = PackageRequired
Server=https://archive.archlinux.org/repos/2022/09/21/$repo/os/$arch
```

**Comment by elParaguayo** [comment] 2022-09-23 21:42
Might need @m-col here. Not aware that we changed anything that would result in this behaviour.

Separately, running `qtile start` from a TTY won't work as it doesn't start the X server. You'd need something like `startx` with an `.xinitrc` file.

**Comment by purutane** [comment] 2022-09-24 07:23
I have the same probolem. I can't start qtile from lightdm.

> Separately, running qtile start from a TTY won't work as it doesn't start the X server. You'd need something like startx with an .xinitrc file.


I wrote the following .xinitrc and confirmed that qtile would start by  startx.
.xinitrc:
```
qtile start
```

**Comment by ervinpopescu** [comment] 2022-09-24 08:33
@sebastienPoussard 

Did you change the Xauthority location when you first installed lightdm?
I remember coming across something like this when I tried to play around with that, but I'm not exactly sure it was this exact error
(`No DISPLAY set`).

Can you try SDDM?

**Comment by purutane** [comment] 2022-09-24 08:49
Hi.

Using sddm as the display manager, qtile was activated.

My friend uses a combination of lightdm and cinnamon. He said that after he upgraded packages, cinnamon would not start.
It seems that there was an update to the lightdm package. This seems to be a lightdm problem, not qtile.

I will use sddm to work around this problem for now.
Thanks.

**Comment by Crystal4276** [comment] 2022-09-24 10:54
There are reports also on reddit about lightdm being broken with other DEs.
Apparently, some could fix the issues using the lightdm-gtk-greeter.

**Comment by Crystal4276** [comment] 2022-09-24 10:55
There are reports also on reddit about lightdm being broken with other DEs.
Apparently, some could fix the issue using the lightdm-gtk-greeter.

**Comment by elParaguayo** [comment] 2022-09-24 13:11
Closing as this seems to be a lightdm issue. Feel free to reopen if there is a qtile specific issue here.

**Closed by elParaguayo** 2022-09-24 13:11 UTC
Labels: unconfirmed

**Comment by sebastienPoussard** [comment] 2022-09-26 09:16
It seems to be indeed a lightDM issue, sorry for the inappropriate bug report

**Comment by elParaguayo** [comment] 2022-09-26 09:17
No problem at all.
