### ISSUE TITLE
qtile keyboard shortcuts stop working after exiting emacs

### ISSUE THREAD

**Issue by IzidorM** [qtile/qtile#1188] opened 2018-07-19 14:42 UTC
After upgrading my arch linux pc (qtile to 0.11.1 and emacs to 26.1), exiting emacs or killing it with mod-w will result in qtile keybindings stop working. I need to use the mouse and click to another group. After doing that all the keybindings will start working again. Any idea what the problem might be?

**Comment by leanNiki** [comment] 2018-08-31 13:05
I have the same issue on my pc. Also arch, qtile 0.12.0, emacs 26.1. When closing emacs, without any other windows in that group, all keybindings stop working. When I click on a different Group (in the statusbar), and that group doesn't contain any window either, keybindings will still not work.

If however there exists another window on the same group as emacs, after closing emacs, the other window gets focus, and keybindings still work/never stop working. 

If  there exists another window on a different group (and emacs is the only window in its group), as soon as I close emacs, keybindings don't work. When I click on the other group, the other window gets focus and keybindings work again.

So currently my workaround is to always have a terminal open on my last workspace/group, and to quickly open another terminal before exiting emacs.

**Comment by ramnes** [comment] 2018-11-13 00:31
Duplicate of #755.

(this bug is super weird, tho)

**Closed by ramnes** 2018-11-13 00:31 UTC
