### ISSUE TITLE
Two screens turn to one after falling asleep

### ISSUE THREAD

**Issue by Yasgur99** [qtile/qtile#1796] opened 2020-06-29 19:58 UTC
#927 Issue description

I have two monitors which I used `arandr` to configure orientation. Upon boot, both monitors show two seperate screens as expected. However when the monitors awoken from falling asleep, the two monitors act as one large screen.

Instead of two top bars, one is shared by both screens and when I open new windows, they take up two monitors

**EDIT:** A `lazy.restart()` does reset and fix the issue

# Qtile version

0.15.1

# Stack traces

* `~/.xsession-errors`
http://termbin.com/2p6e
* `~/.local/share/qtile/qtile.log`
http://termbin.com/71ys9

# Configuration
http://termbin.com/x73md

**Comment by fdev31** [comment] 2020-07-02 19:09
I have the same issue when I restart qtile "for real".

**Comment by tych0** [comment] 2020-07-10 01:49
Dupe of #1632, I'll close this in favor of that one.

**Closed by tych0** 2020-07-10 01:49 UTC
