### ISSUE TITLE
Add a config variable to prevent Chromium from restoring its windows in their previous groups

### ISSUE THREAD

**Issue by Alteus** [qtile/qtile#2422] opened 2021-04-26 20:30 UTC
Hi,

Qtile has a strange behaviour on my system. It affects Brave and Chromium browsers.

When "continue where you left off" option is turned on in the browser, the first instance of the browser opens always in the group where it was closed last time, instead of the active group. The second browser instance opens normally in the active group.

I don't have any rules in config.py for these apps (only one keybind for Brave). Other apps (including Firefox) are just fine. Tried different layouts, same behaviour.
[config.py.zip](https://github.com/qtile/qtile/files/6380038/config.py.zip)

Vanilla Arch, Qtile version: 0.17.0-1

**Comment by ramnes** [comment] 2021-04-27 08:18
It's not a bug, it's a feature. :)

**Comment by Alteus** [comment] 2021-04-27 08:59
> It's not a bug, it's a feature. :)

I appreciate the joke, but then the bug is in the handling of Firefox. :p

**Comment by ramnes** [comment] 2021-04-27 09:16
Nah, it's just that Firefox developers decided not to leverage these EWMH (I think?) features. But Chromium developers did.

**Comment by Alteus** [comment] 2021-04-27 09:24
I understand, but this "feature" is simply irritating. Browser should remember the opened pages across restarts, but the window and group handling is the job of the WM. I didn't experience this before on bspwm and I3wm .

**Comment by ramnes** [comment] 2021-04-27 09:42
Well, I guess that means we support some parts of the spec that bspwm and i3 don't. We could probably add a toggle as a config variable though, I think we've had other people complaining about this already. PR welcome!

**Comment by m-col** [comment] 2021-04-27 11:39
Perhaps I misunderstood, but isn't this already configurable... in Chromium?

**Comment by Alteus** [comment] 2021-04-27 12:26
The mentioned option controls the reopening of pages in Chromium **and** starting Chromium itself in the last used group. The issue is only about the last part, but currently these two are inseparable.

**Comment by m-col** [comment] 2021-04-27 13:26
Ah OK, got it.

**Comment by Alteus** [comment] 2021-04-27 13:53
One last observation: I can't override the location with @hook.subscribe.client_new either for a quick hack.

**Comment by m-col** [comment] 2021-04-27 15:51
What about `client_managed`? It is fired a little later.

**Comment by Alteus** [comment] 2021-04-27 18:19
My bad, I had a typo.

`@hook.subscribe.client_new
def browser(c):
     if c.window.get_wm_class() == ('chromium', 'Chromium'):
        c.togroup("5")`

This definitely overrides the setting in Chromium and sends it to group 5.
How do I refer to the active group name in qtile? I don't find that anywhere.

**Comment by m-col** [comment] 2021-04-27 18:23
`c.qtile.current_group.name` I think

**Comment by Alteus** [comment] 2021-04-27 18:39
That's it!

```
@hook.subscribe.client_new
def browser(c):
    if c.window.get_wm_class() == ('chromium', 'Chromium'):
       c.togroup(c.qtile.current_group.name)
```

This is the final hack then. Thanks!

**Comment by ramnes** [comment] 2021-04-28 09:32
Looks like a good workaround. :)

I'll close this for now, but feel free to comment here if you're in the same boat and not satisfied with this hook for some reason.

**Closed by ramnes** 2021-04-28 09:32 UTC
Labels: enhancement, help wanted
