### ISSUE TITLE
systray disappears randomly

### ISSUE THREAD

**Issue by 0ion9** [qtile/qtile#813] opened 2015-11-21 00:14 UTC
Not sure what else to say about this. The disappearance is triggered by either launching an application or switching group; the way systray is being used is pretty vanilla AFAICS. Applications in it at the time of disappearance are usually Zim and Kupfer, occasionally also GPick.

[config file, with some long comments removed for brevity](https://gist.github.com/0ion9/ca97e76fc7f53b72bb9c). There are a few references to stuff on my specific system, but this shouldn't affect things. However the config is designed for a Colemak keyboard layout, which you definitely should be aware of before testing (eg mod+n/e to switch between windows, etc)

EDIT:
using qsh, inspecting the info for the bottom bar shows:

```
{'height': 30,
 'length': 1680,
 'position': 'bottom',
 'size': 30,
 'widgets': [{'foreground': 'ffffff',
              'height': 30,
              'length': 197,
              'name': 'groupbox',
              'offset': 0,
              'text': ' ',
              'width': 197},
             {'foreground': 'ffffff',
              'height': 30,
              'length': 0,
              'name': 'prompt',
              'offset': 197,
              'text': '',
              'width': 0},
             {'foreground': 'ffffff',
              'height': 30,
              'length': 1361,
              'name': 'windowname',
              'offset': 197,
              'text': 'sakura',
              'width': 1361},
             {'foreground': 'ffffff',
              'height': 30,
              'length': 12,
              'name': 'info',
              'offset': 1558,
              'text': ' ',
              'width': 12},
             {'float_info': {'h': 1, 'w': 1, 'x': -1, 'y': -1},
              'floating': False,
              'fullscreen': False,
              'group': None,
              'height': 1,
              'id': 10486127,
              'maximized': False,
              'minimized': False,
              'name': '<no name>',
              'width': 1,
              'x': -1,
              'y': -1},
             {'foreground': 'ffffff',
              'height': 30,
              'length': 0,
              'name': 'notify',
              'offset': 1570,
              'text': '',
              'width': 0},
             {'foreground': 'ffffff',
              'height': 30,
              'length': 110,
              'name': 'clock',
              'offset': 1570,
              'text': '2015-11-21 Sat 10:44 AM',
              'width': 110}],
 'width': 1680,
 'window': 10486108}
```

Which I think is saying that the systray has no name and 'no' position?

**Comment by rocha** [comment] 2016-04-07 13:00
I am having the same issue, but constantly. On my system, `qsh` is reporting the same as @flacjacket :

```
widget['systray']> info
{'float_info': {'height': 1, 'width': 1, 'x': None, 'y': None},
 'floating': False,
 'fullscreen': False,
 'group': None,
 'height': 20,
 'id': 25166115,
 'maximized': False,
 'minimized': False,
 'name': '<no name>',
 'width': 100,
 'x': -1,
 'y': -1}
```

**Comment by flacjacket** [comment] 2016-04-12 17:00
That is correct, the window associated with the systray is just there to select the `_NET_SYSTEM_TRAY_S0` atom. As programs register with the systray, it creates `Icon` windows, which is what it actually displays.

**Comment by flacjacket** [comment] 2016-04-12 17:03
As for why it disappears, that is harder to say, @rocha: what qtile version are you running? is there anything showing up in the log file? when you say constantly, do you mean it never shows up, or that it does show up but drops out a lot?

**Comment by rocha** [comment] 2016-04-14 13:33
Hi @flacjacket. I am using v0.10.5.  Nothing is shown in the tray at any moment. I think the systray widget is being drawed (there is some space between the adjacent widgets).

The only warnings/errors on the log are related to DBbus. 

I trying to get something prior to v.0.10.2 to run in my system and check if the problem is also there.

**Comment by rocha** [comment] 2016-04-14 15:23
Poking around a little bit more, it seems like I have a DBUS session problem. The error message I get is the same as in #904, which I think is unrelated.

My problem is the same as the one described [here](https://bugs.launchpad.net/ubuntu/+source/dbus/+bug/1120526) were the `DBUS_SESSION_BUS_ADDRESS` variable is set to the an incorrect value. Once the variable is fixed in `.xsession` script, the systray works correctly.

**Comment by 0ion9** [comment] 2017-03-16 00:53
I've just noticed something that probably relates to this:

I think the widget gets a negative offset so that it is "drawn" off the left of the screen. The reason I say this is that I recently added another icon to my system tray (totalling 3 icons now), and the 'disappearance' glitch has just occurred minutes ago.. but the rightmost icon is still visible + can be clicked on as usual. It is drawn over the desktop switcher.

![image](https://cloud.githubusercontent.com/assets/115782/23976874/8ca6c4ee-0a3a-11e7-90bf-c3907bf2ba7f.png)

(as you can see, the application I recently added is CopyQ. The letter that is being obscured by the icon is 'a'. The apparent offset of the left corner of the systray seems to be -40, given the visible size of the CopyQ icon (20x20) and the fact that two icons are not shown).

To me this suggests that the problem may be more general than the system tray -- should any widget at all be able to get negative offset?

**Comment by ramnes** [comment] 2018-11-19 01:51
@0ion9 Is this still the case with Qtile 0.12?

As I said on #465, since those two issues are very close: I used to have this bug very often (and I used to complain very often about it), but I don't have it anymore, so I'll go ahead and close this. Please ping me here if you're still affected by this bug while running Qtile 0.12+ and I'll reopen the issue.

**Closed by ramnes** 2018-11-19 01:51 UTC
Labels: widgets

**Comment by 0ion9** [comment] 2018-11-20 01:10
It's currently unclear to me whether this bug is still applicable, as I do keep up with qtile git version, but no longer typically run apps that use the systray. I'll do a week's testing with Zim started at the beginning of each session and report back if necessary.

**Comment by ramnes** [comment] 2018-11-20 10:52
Thank you @0ion9!

**Comment by 0ion9** [comment] 2018-12-01 23:49
Reporting back, I've had no problems with the systray during this period, so I agree that the bug appears to be fixed :)
