### ISSUE TITLE
Something is wrong with the mouse focus of certain windows

### ISSUE THREAD

**Issue by TinyAtoms** [qtile/qtile#3765] opened 2022-08-14 04:14 UTC
### The issue:

Something is wrong with the focus of firefox windows

# Problem 
The issue is a bit hard to describe, and similar to [this issue](https://github.com/qtile/qtile/issues/1152). I have tried the proposed fixes over there, but they don't work. It might also be the same as #3697 but that one doesn't mention it only happens to specific windows.

Say I have windows open with following group and layouts:
|firefox|terminal| <- group 1
| spotify| terminal| <- group 2
|librewolf| terminal| -< group 3
When I try to interact with spotify in group 2, when it is supposed to be in focus and the border color is making it clear it is focused, none of my clicks register there, instead they go to firefox. 
Same if I try to interact with librefox, they go to firefox. 
Well, to say that they go to firefox is a simplification.  It goes to whichever of [firefox/spotify/librefox] was opened first. If I open firefox and then spotify, the clicks from spotify go to firefox, but if I open spotify and then firefox, the clicks of firefox go to spotify.
I have tried it with `follow_mouse_focus` true and false since the mentioned issue specifically mentions that, but it makes no difference.

## Affected apps
discord-canary (discord_arch_electron from AUR does not have the issue)
firefox
librewolf
spotify

# Environment
Qtile for wayland on Arch linux. 
qtile 0.21.0
wlroots 0.15.1-6
firefox 103.0.2-1
librewolf-bin 103.0.201 (AUR)
spotify 1:1.1.84.716-2
Dunno if you need these, but here they are
wayland 1.21.0-1
wayland-protocols 1.26-1
xorg-xwayland 22.1.3-1
python-pywayland 0.4.14-1

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment] 2022-08-14 09:51
Please could you test with the git master version of Qtile to see if it persists? We had a similar issue which was (at least partially) resolved.

Are you running firefox with `MOZ_ENABLE_WAYLAND=1`?

**Comment by TinyAtoms** [comment] 2022-08-14 15:04
Launching firefox and librewolf with `MOZ_ENABLE_WAYLAND=1 firefox/librewolf` does fix the issue for them. 
I will try out the git master version later today to check if the issue is present between discord-canary and spotify, since I can't set flags for those.

**Comment by TinyAtoms** [comment] 2022-08-14 20:17
The issue is not present in https://aur.archlinux.org/packages/qtile-wayland-git which pulls uses the master git, right?

**Comment by 3nprob** [comment] 2022-08-17 04:38
Looks like duplicate of #3697 and #3675. As noted this issue appears for xwayland windows under wayland.

So @TinyAtoms it would be expected that this bug stops affecting you for Firefox when you start running it natively under Wayland.

**Comment by m-col** [comment] 2022-10-28 23:30
> The issue is not present in https://aur.archlinux.org/packages/qtile-wayland-git (which uses the master branch of this repo, right?)

Yep exactly.

> Looks like duplicate of https://github.com/qtile/qtile/issues/3697 and https://github.com/qtile/qtile/issues/3675. As noted this issue appears for xwayland windows under wayland.

Cool, makes sense. Closing in favour of those issues. Thanks for the report :)

**Closed by m-col** 2022-10-28 23:30 UTC
Labels: bug, Wayland
