### ISSUE TITLE
Problem running qtile under debian

### ISSUE THREAD

**Issue by s-hell** [qtile/qtile#831] opened 2015-12-17 08:15 UTC
There seems to be a problem running qtile under debian.

https://paste.pcspinnt.de/view/cdfb8508

Tried it with the gitub version and the version from the package repository. Same error.

**Comment by flacjacket** [comment] 2015-12-17 16:34
Try replacing the line where that ImportError is raising ([here](https://github.com/qtile/qtile/blob/develop/libqtile/pangocffi.py#L59)) with just `raise`, then we can see what exactly the problem is. That error comes up when the ffi build scripts aren't run and people try to run from source, but it looks like you're using an installed version, so that isn't it.

**Comment by ThomasWaldmann** [comment] 2016-02-08 05:27
@s-hell the pastebin is gone.

**Comment by tych0** [comment] 2016-03-03 16:31
Going to close this for now since the pastebin is dead.

**Closed by tych0** 2016-03-03 16:31 UTC
