### ISSUE TITLE
tooltips are placed partially off-screen

### ISSUE THREAD

**Issue by PhoenixClank** [qtile/qtile#3533] opened 2022-04-28 20:24 UTC
### The issue:

Tooltips, for example when hovering over a file in PCManFM, or over a long video title in YouTube, will be placed partially off-screen when they are spawned near the right edge of the screen. Notably, this does not happen near the bottom edge; the window knows when to spawn above the mouse pointer.

I'm running qtile 0.21.0, as a Wayland compositor, on Arch.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment] 2022-05-02 22:43
I'm unsure if this is a bug in Qtile because it all seems to be set up fine. Does this happen with all popups or just those belonging to certain programs? Which browser do you see the problem with?

I only seem to see this with Anki, which uses Qt 5.15.2 & PyQt 5.15.6. I can reproduce the problem with PCManFM-Qt. Is your copy also the Qt version?

**Comment by PhoenixClank** [comment] 2022-05-03 08:27
The browser I'm using is Firefox. Yes, I'm using PCManFM-Qt.

**Comment by m-col** [comment] 2022-05-03 10:27
I can't reproduce with firefox. Please could you post a screenshot of an example where it's happening?

**Comment by Sydiepus** [comment] 2022-05-03 16:45
Not sure if this is related but i have a similar issue. 
I'm using firefox with Xwayland.
![image](https://user-images.githubusercontent.com/49863809/166499886-dec6e9bd-ae04-4143-b723-6e582afc6f0c.png)
The right click menu also never changes position it always spawn at the first location.

**Comment by PhoenixClank** [comment] 2022-05-03 21:08
The mouse pointer isn't included in the screenshot; it's hovering on the word "Still" of the Portal & Portal 2 video's title.
![20220503_23h02m23s_grim](https://user-images.githubusercontent.com/30195074/166566231-ec44e954-9129-4881-8a1b-20d1e6341384.png)

**Comment by m-col** [comment] 2022-05-28 15:41
@Sydiepus I've opened a specific issue for your issue: https://github.com/qtile/qtile/issues/3594. It's similar in symptom but the underlying cause (and therefore fix) will be different I think.

**Comment by Sydiepus** [comment] 2022-05-28 15:57
Oh, thanks.

I'll subscribe to the issue and test any possible patches.

**Comment by PhoenixClank** [comment] 2022-06-15 20:49
I fixed this accidentally by commenting out the assertion you removed in https://github.com/qtile/qtile/commit/ea531114fba129096a5cf1efebf8e6883f62725d
So that seems to have been the fix, but it hasn't arrived in my distribution's release of qtile yet.

Also to note is that a popup can still reach out of the screen if a program re-uses the same popup window but enlarges it (for example in PCManFM-Qt hovering over a short file and then quickly a nearby one with a longer filename).

**Comment by m-col** [comment] 2022-06-26 00:02
> Also to note is that a popup can still reach out of the screen if a program re-uses the same popup window but enlarges it (for example in PCManFM-Qt hovering over a short file and then quickly a nearby one with a longer filename).

I suspect this issue will also be fixed by https://github.com/qtile/qtile/issues/3594, because then we're respecting geometry changes of the popups.

As the original issue should be fixed by https://github.com/qtile/qtile/commit/ea531114fba129096a5cf1efebf8e6883f62725d, should we close this?

I'm actually 100% certain it is fixed though, as I think I do sometimes see this issue?

**Comment by PhoenixClank** [comment] 2022-06-26 10:17
I noticed another thing: window A's popups appear behind window B if window B was opened after window A (see screenshot). If you want me to open a new issue for that you can close this one.
![20220626_12h13m10s_grim](https://user-images.githubusercontent.com/30195074/175809556-3c43fd5b-3d86-4a41-9e75-68ff3dc6dac2.png)

**Comment by m-col** [comment] 2022-06-26 11:36
Huh! I guess this is due to the Z axis control. If you click on the window on the left, do its popups then open up at the front as expected?

**Comment by PhoenixClank** [comment] 2022-06-26 12:07
Yes, if I set `bring_front_click = True` (which I don't normally because it puts tiling windows in front of floating ones).

**Comment by m-col** [comment] 2022-06-26 13:08
If these two windows were overlapping by a lot, e.g.:
```

  ┌───┬──────────┬─────┐
  │   │          │     │
  │   │          │     │
  │   │          │     │
  │   │          │     │
  │   │          │     │
  │   │          │     │
  └───┼──────────┘     │
      │                │
      │                │
      └────────────────┘

```
with the smaller window on the left behind the window on the right, and the smaller window opened a popup tooltip, would you expect it to appear in front of or behind the larger window?

**Comment by PhoenixClank** [comment] 2022-06-26 14:30
I'd expect tooltips to be in front of everything else, even in this example.
Though now that you ask this way, I understand if people expect a window's tooltips to be at the same z position as that window. So maybe it should be an option.

**Comment by m-col** [comment] 2022-10-28 23:20
I've made a dedicated issue for the popup Z axis issue here: https://github.com/qtile/qtile/issues/3936

I think the main issue of misplaced popups has been fixed, so I'll close this. If I'm mistaken please feel free to re-open :)

**Closed by m-col** 2022-10-28 23:20 UTC
Labels: Wayland
