### ISSUE TITLE
wine broke screen 

### ISSUE THREAD

**Issue by ArchKubi** [qtile/qtile#3275] opened 2022-01-30 04:30 UTC
group screen broken now

![2022-01-30-071744_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151686660-5d602f71-f441-4183-9b64-0f0f5236f9fd.png)
![2022-01-30-071920_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151686661-6ac63d3d-772d-406e-9b41-5f2fa3d9390c.png)
![2022-01-30-072901_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151686664-bf34ffd4-1bdc-428b-8a8d-886138ec0b19.png)
![2022-01-30-072506_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151686662-b5e1da47-d211-4cf6-9f20-aa7fc69f4175.png)
![2022-01-30-072847_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151686663-cb13bfe0-8e00-4609-951b-ceec79516e37.png)

**Comment by m-col** [comment] 2022-01-30 11:25
Is this a duplicate of https://github.com/qtile/qtile/issues/3266?

**Comment by ArchKubi** [comment] 2022-01-30 12:19
nope this time group 3 freezes

**Closed** 2022-01-31 02:56 UTC
