### ISSUE TITLE
Qtile can't in hotkeys with subprocess

### ISSUE THREAD

**Issue by superpupervlad** [qtile/qtile#1834] opened 2020-07-22 21:57 UTC
# Issue description
When I use subprocess as Key command it makes an error. 
I tried to use subprocess because it successfully used [in docs](http://docs.qtile.org/en/v0.15.1/manual/config/hooks.html?highlight=subprocess.call#autostart). And i can't find any information about this 'limitation'. Also I didn't use lazy.spawn because I thought that this only for installed application like browser. So maybe need to add more information about this to docs.

# Qtile version
0.15.1-1
I install qtile on arch via pacman, so i don't know exact commit.
PKGBUILD says it was downloaded from this url: https://github.com/qtile/qtile/archive/v0.15.1.tar.gz

# Stack traces
2020-07-22 21:29:00,310 ERROR libqtile xcore.py:_xpoll():L277 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/backend/x11/xcore.py", line 246, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.8/site-packages/libqtile/backend/x11/xcore.py", line 494, in handle_KeyPress
    self.qtile.process_key_event(keysym, event.state & self._valid_mask)
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 329, in process_key_event
    key = self.keys_map[(keysym, mask)]
KeyError: (114, 65)

# Configuration
`scripts_path = os.path.expanduser('~/.config/qtile/scripts/')`

`Key([], "XF86MonBrightnessDown", subprocess.call([scripts_path + 'dec_brightness.sh'], shell=True))`
or with run and without shell
`Key([], "XF86MonBrightnessDown", subprocess.run([scripts_path + 'dec_brightness.sh']))`

**Comment by ramnes** [comment] 2020-07-22 22:15
Hey @superpupervlad. welcome to Qtile!

What's happening here is that you're calling your scripts when the config is being loaded, and you're giving the result of `subprocess.call(...)` as an argument of `Key`. It's just how Python (and most interpreters or compilers) reads code, it's completely unrelated to Qtile. The example you linked do use `subprocess.call`, but it's inside a hook function, so it's only executed when the hook is called by Qtile, not when the config is being loaded.

At the very least, you have to wrap this with `lazy.function`, but I think you should really use `lazy.spawn`. Why did you feel it wasn't possible to use it here? Feel free to modify the documentation if something misguided you.

I'll go ahead and close this as it's definitely not a bug, but feel free to continue the discussion and open a PR for the docs.

**Closed by ramnes** 2020-07-22 22:15 UTC
