### ISSUE TITLE
Crash when switching from Chrome full-screen using Slice layout

### ISSUE THREAD

**Issue by imiric** [qtile/qtile#338] opened 2013-08-19 21:14 UTC
Hi,

while in the Slice layout, if you switch to full-screen in Chrome (F11) and then switch back, Qtile will crash with the following stack trace:

```
2013-08-19 23:05:52,527 ERROR _xpoll:568 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 564, in _xpoll
    r = h(e)
  File "/usr/lib/python2.7/site-packages/libqtile/window.py", line 1055, in handle_ClientMessage
    self.fullscreen = (fullscreen_atom in current_state)
  File "/usr/lib/python2.7/site-packages/libqtile/window.py", line 709, in fullscreen
    self.disablefloating()
  File "/usr/lib/python2.7/site-packages/libqtile/window.py", line 881, in disablefloating
    self.group.mark_floating(self, False)
  File "/usr/lib/python2.7/site-packages/libqtile/group.py", line 226, in mark_floating
    i.focus(win)
  File "/usr/lib/python2.7/site-packages/libqtile/layout/max.py", line 48, in focus
    self.group.layoutAll()
  File "/usr/lib/python2.7/site-packages/libqtile/group.py", line 83, in layoutAll
    self.layout.layout(normal, screen)
  File "/usr/lib/python2.7/site-packages/libqtile/layout/slice.py", line 88, in layout
    self._fallback: sub,
  File "/usr/lib/python2.7/site-packages/libqtile/layout/base.py", line 210, in delegate_layout
    lay = self.layouts[w]
KeyError: Window(New Tab - Google Chrome)
2013-08-19 23:05:52,530 WARNING loop:603 Got exception, Breaking main loop
```

This seems like a simple fix, but not being familiar with the code it'll probably take me much more than if someone who is took a look at it.

Thanks!

**Comment by m-col** [comment] 2021-01-09 20:55
I cannot reproduce this (either exception or crash) and it's been 6 years so I'll close this as it's unlikely still an issue. If this is still a problem, please reopen.

**Closed by m-col** 2021-01-09 20:55 UTC
Labels: bug, fullscreen
