### ISSUE TITLE
Firefox context menus are cut off

### ISSUE THREAD

**Issue by bendi-github** [qtile/qtile#4877] opened 2024-06-12 15:26 UTC
### Issue description

Context menus in Firefox are cut off. The cut off parts are still interactable.
![image](https://github.com/qtile/qtile/assets/83127964/5a98fe8c-102c-4bd2-b6b7-8af1bfa68fe9)
![image](https://github.com/qtile/qtile/assets/83127964/e8183764-7df8-4298-8be5-2ce0dcb2dba8)
The context menus are rendered correctly on hyprland.

### Version

\0.23.0b3.dev350+g6ee02e5c

### Backend

Wayland (experimental)

### Config

```python
Default config
```

### Logs

```text
Nothing appears when invoking a popup via rightclick
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment] 2024-06-12 15:59
Duplicate of #4819

**Comment by jwijenbergh** [comment] 2024-06-12 15:59
I have edited that issue to indicate that it might not only be during resizing

**Closed by jwijenbergh** 2024-06-12 15:59 UTC
Labels: status: unconfirmed
