### ISSUE TITLE
Old groups remain after lazy.restart()

### ISSUE THREAD

**Issue by EffToyz** [qtile/qtile#1874] opened 2020-08-19 04:33 UTC
# Issue description

When I change group names and do ` lazy.restart() ` I have both old and new groups. Plus, if I have an error in config.py I get "asdfuiop" groups from default config and after fixing errors and another ` lazy.restart() ` I have my groups and additional 8 groups. They are not only in **GroupBox** widget, ` qtile-cmd -o cmd -f groups ` also shows old group on the list.

# Qtile version

0.15.1 from Manjaro distro, also have this issue with 0.16.2.dev8+gbe769d82

# Stack traces

Restart gives no errors stack traces, only a warning.
`2020-08-19 00:16:37,217 WARNING libqtile manager.py:maybe_restart():L269 Restarting Qtile with os.execv(...)`

# Configuration 

I set groups like this:

```
group_names = [
    ("Term ", {'layout': 'matrix'}),
    ("Dev ", {'layout': 'max'}),
    ...
]

groups = [Group(name, **kwargs) for name, kwargs in group_names]

for i, (name, kwargs) in enumerate(group_names, 1):
    keys.append(Key([mod], str(i), lazy.group[name].toscreen()))
    keys.append(Key([mod, "shift"], str(i), lazy.window.togroup(name)))
```

**Comment by m-col** [comment] 2020-08-19 11:34
I can reproduce and have tracked it to the pickling of state between restarts :)

**Comment by m-col** [comment] 2020-08-19 11:44
Looks like [here](https://github.com/qtile/qtile/blob/master/libqtile/state.py#L64) we are re-adding groups stored in QtileState that aren't found in the new Qtile instance. @tych0 @ramnes Should we not drop orphaned windows to the first group instead?

**Comment by ramnes** [comment] 2020-08-19 14:07
Duplicate of #1315

@tych0 thinks it's not a bug: https://github.com/qtile/qtile/pull/1391#issuecomment-623138218

**Comment by ramnes** [comment] 2020-08-19 14:09
> Should we not drop orphaned windows to the first group instead?

I think it would a much saner behavior, yes.

**Comment by tych0** [comment] 2020-08-19 14:27
I don't think it's sane: if you add a group via dgroups (or any other mechanism) that isn't in your new config, a restart destroys that without the above behavior.

**Comment by tych0** [comment] 2020-08-19 14:28
What we could do is only add these groups back if they contain windows? Presumably anyone using dgroups in this manner has code to re-create the groups if they're needed.

**Comment by m-col** [comment] 2020-08-19 14:46
Ah I see. I've not used dgroups, but would people who do find it useful to have a setting to set whether or not their dgroups are reset or persist across a restart?

> Presumably anyone using dgroups in this manner has code to re-create the groups if they're needed.

This could also be used to argue for resetting all dgroups even with windows.

I don't mind either way; it seems like the issue is more about awareness of how it works :)

**Comment by tych0** [comment] 2020-08-19 14:56
I think people restart for two reasons:

1. a new monitor was attached (since we don't handle this gracefully, we just punt and tell people to figure it out in their configs dynamically)
2. testing/developing their configs.

The complains about this bug come from people doing 2, and if we change the behavior, we'll get complaints from people doing 1. Seems like the "real" fix for this would be to gracefully handle screen attach, so we could stop recommending people restart for case 1, as it's clunky anyway :)

**Comment by tych0** [comment] 2020-08-19 14:59
To be clear: I would have no problem changing this behavior if we can gracefully handle screen attach/detach somehow.

**Comment by DorianGray** [comment] 2021-01-08 16:05
would this specific issue be solved if we added and honored a flag to groups that caused them to survive restarts, and any group without that flag would be removed? I'm happy to implement it if so.

**Comment by tych0** [comment] 2021-01-08 16:10
IMO, best to just fix the reconfigure thing on restart, and then we can drop this behavior entirely instead of adding another flag.

**Closed** 2021-03-16 21:13 UTC
Labels: X11, bug, in progress, multimonitor
