### ISSUE TITLE
Wev  crashes "Error marshalling request: Too many open files"

### ISSUE THREAD

**Issue by bendi-github** [qtile/qtile#4878] opened 2024-06-12 20:32 UTC
### Issue description

When running wev to debug input events, the log gets filled up with 
```
[09:     xdg_surface] configure: serial: 32353
[10:    xdg_toplevel] configure: width: 848; height: 330
                      activated tiled-left tiled-right tiled-top tiled-bottom
```
and eventually crashes
```
error marshalling arguments for create_pool: dup failed: Too many open files
Error marshalling request: Too many open files
```
Input events are still logged while the log is being spammed.

### Version

0.23.0b3.dev350+g6ee02e5c

### Backend

Wayland (experimental)

### Config

```python
Default, I just changed the modkey to `mod1` for testing
```

### Logs

Nothing shows up, besides the usual warnings the default config throws on wayland

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment] 2024-06-15 09:24
`0.23.0b3.dev350+g6ee02e5c`

that is a really old version, please test on the latest

**Comment by bendi-github** [comment] 2024-06-15 12:31
```bash
git clone https://github.com/qtile/qtile.git
cd qtile
pip install .
pip install --config-setting backend=wayland . 
```
`qtile-0.26.1.dev25+g29695c71`

The issue persists. I tested a nested qtile instance in additon to starting it directly via sddm. I noticed when I launched wev in a nested session, it crashed faster when compared to a non-nested session.

**Comment by tych0** [comment] 2024-06-15 15:27
I wonder if this is really a dupe of #4821, that we're leaking stuff when certain events happen, and in the wev model these things end up as file descriptors?

**Comment by jwijenbergh** [comment] 2024-06-15 16:56
#4880 fixes this for me

**Comment by jwijenbergh** [comment] 2024-06-15 16:58
> I wonder if this is really a dupe of #4821, that we're leaking stuff when certain events happen, and in the wev model these things end up as file descriptors?

I doubt it, this seems like a recent regression in git

**Closed** 2024-06-17 07:08 UTC
Labels: status: unconfirmed
