### ISSUE TITLE
Start up hooks dont work

### ISSUE THREAD

**Issue by steveieme** [qtile/qtile#1169] opened 2018-04-18 10:35 UTC
Hi I have been stuck on this for weeks and I am at the end of my tether hoping someone can help. I have recently started using Qtile and I love it but I cannot get any of the below to startup any of the apps for my systray i.e. nm-applet etc...

@hook.subscribe.startup
@hook.subscribe.startup_once
@hook.subscribe.startup_complete 

*********************************************************************************

the code I am using is -

@hook.subscribe.startup_once
def startup_once():
subprocess.Popen(["nm-applet"])

thanks

**Comment by flacjacket** [comment] 2018-04-27 01:55
That is very odd. If you run that after qtile has started, does it work as expected?

**Comment by soulchainer** [comment] 2018-10-23 17:43
This may not be a direct answer for what you're seeking, @steveieme,  but just in case it's of some help.
I'm running several apps on startup via Qtile and I do it this way:

I have a bash file like this (well, in fact, exactly this one xD), with executable permission:

```sh
#!/bin/bash
nm-applet &
firefox &
firefox-developer-edition &
```

Then, in my `config.py`:

```py
from libqtile import hook
# some other imports
import os
import subprocess
# stuff
@hook.subscribe.startup_once
def autostart():
    home = os.path.expanduser('~/.config/qtile/autostart.sh') # path to my script, under my user directory
    subprocess.call([home])
```

This works for me and I have been using it for a long time. Plus, if I want, I can use the `autostart.sh` with other wm also.

**Comment by FrostyX** [comment] 2018-11-04 14:04
The @soulchainer solution is also described in the documentation
http://docs.qtile.org/en/latest/manual/config/hooks.html#autostart

**Comment by ramnes** [comment] 2018-11-11 01:17
I just can't reproduce. :disappointed: 

@steveieme, I just took the default config and added your snippet, and it works, nm-applet is there.

Can you give more details about your environment? OS and Qtile version, to begin with?

**Comment by codeforcesmeme** [comment] 2019-11-20 17:40
I thought this happened to me but turns out (stupid me) was using startup_once hook and restarting qtile expecting nm-applet to start Ha.
I think @steveieme is the same case? I don't think there is an issue with qtile regarding this matter

**Comment by ramnes** [comment] 2019-11-21 14:14
Might be, yeah. OP isn't answering anyway so I'm going to close this. Feel free to ping me if this is an issue to anyone else so that I can reopen, or to start another thread mentioning this issue. Thanks!

**Closed by ramnes** 2019-11-21 14:14 UTC
Labels: bug, unconfirmed

**Comment by Ficklampan** [comment] 2020-08-29 10:23
@ramnes 
i have this issue

```
@hook.subscribe.startup
def autostart():
    home = os.path.expanduser('~/.config/qtile/autostart.sh')                            
    subprocess.call([home])
```

i don't get any errors. the autostart.sh should start firefox and wallpaper thing (just for testing) but nothing happens:(

**Comment by Ficklampan** [comment] 2020-08-29 11:24
i also tested:
```
@hook.subscribe.startup
def autostart():
    lazy.spawn("firefox")
```
and no result:(

**Comment by Ficklampan** [comment] 2020-08-29 11:32
looks like no hook works

**Comment by m-col** [comment] 2020-08-29 11:38
Try this to get the output of the command:

```
from libqtile.log_utils import logger

@hook.subscribe.startup
def autostart():
     output = subprocess.check_output(
	os.path.expanduser('~/.config/qtile/autostart.sh'),
	shell=True
     ).decode('utf-8')
     logger.error(output)
```

Then anything the script outputs will go into the qtile log. Maybe something
useful is there?

**Comment by m-col** [comment] 2020-08-29 11:50
FWIW, on master this works for me to show that hooks are working:

```
@hook.subscribe.startup
def _():
    logger.warning("STARTUP")

@hook.subscribe.client_new
def _(c):
    if not hasattr(qtile, 'var'):
        qtile.var = 0
    qtile.var += 1
    logger.warning(qtile.var)
```

**Comment by Ficklampan** [comment] 2020-08-29 12:30
hmmmmmmm i got this error:

```
2020-08-29 14:28:36,717 libqtile hook.py:fire():L367  Error in hook startup
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/hook.py", line 365, in fire
    i(*args, **kwargs)
TypeError: autostart() missing 1 required positional argument: 'window'
```

when i run $``qtile`` (can't find the logs:) )

**Comment by m-col** [comment] 2020-08-29 12:35
Looks like the `autostart` function you have defined takes an argument (`def autostart(window):`), but the startup hook doesn't pass any arguments, so you need to remove 'window'

**Comment by Ficklampan** [comment] 2020-08-29 12:44
i removed it. but now i get a 'permission denied' to ``~/.config/qtile/autostart.sh`` hmmhm

**Comment by m-col** [comment] 2020-08-29 12:49
Ah OK. That probably means that it isn't executable. Run `chmod +x ~/.config/qtile/autostart.sh` in a terminal and then try it again

**Comment by Ficklampan** [comment] 2020-08-29 12:53
it works thank you! :D

**Comment by m-col** [comment] 2020-08-29 12:57
No probs :)
