### ISSUE TITLE
Wallpaper flashes briefly when managing windows

### ISSUE THREAD

**Issue by ZakDggn** [qtile/qtile#4586] opened 2023-11-19 15:47 UTC
### Issue description

The background wallpaper briefly flashes on the screen when managing windows. This is especially noticeable when switching windows in the Max layout but also happens when creating, closing and moving windows in other layouts. The problem persists after reverting to the default config or using the qtile-git AUR package.

https://github.com/qtile/qtile/assets/23458039/c3d82d90-6a98-4996-811e-2bcc61a3ab85

### Version

0.23.0-1

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jwijenbergh** [comment] 2023-11-19 16:38
I can see why this is an issue but I doubt we will do anything about such a minor thing on the x11 backend. Maybe on wayland we don't want this behaviour due to it striving to be pixel perfect

That being said, contributions welcome here

**Comment by ZakDggn** [comment] 2023-11-19 19:16
I'd be interested in giving it a go, where would be a good place to start trying? [libqtile/backend/x11/drawer.py](https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/drawer.py)?

**Comment by elParaguayo** [comment] 2023-11-19 19:22
On the Max layout, what happens if you set `only_focused=False`?

I imagine the issue is because the current window is hidden and there's a brief pause before the next one is displayed. Using `only_focused=False` means all windows are displayed in the layout. Note: this will look ugly if your windows have transparency as you'll see the windows underneath.

> I'd be interested in giving it a go, where would be a good place to start trying? [libqtile/backend/x11/window.py](https://github.com/qtile/qtile/blob/master/libqtile/backend/x11/window.py)?

This isn't a drawer issue (qtile isn't drawing anything here). I'm pretty sure it's just a layout timing issue.

**Comment by jwijenbergh** [comment] 2023-11-19 19:22
I think a good place to start is the max layout https://github.com/qtile/qtile/blob/master/libqtile/layout/max.py

You would have to do something smart like first laying out the focused window and moving it to top, before hiding the previously focused window. The group code is important here too

https://github.com/qtile/qtile/blob/master/libqtile/group.py

Maybe this is not as backend specific as I initially thought, so if there is a clean way to fix it in those places then both Hacienda would benefit

**Comment by ZakDggn** [comment] 2023-11-19 19:56
> On the Max layout, what happens if you set `only_focused=False`?

Yes, thank you, that fixes it for the Max layout.
It's less noticeable in the tiling layouts but I'll have a look to see if I can work anything out.

**Comment by elParaguayo** [comment] 2023-11-26 09:46
I'll close this for now. Happy to look at a pull request if you change any of the layouts.

**Closed by elParaguayo** 2023-11-26 09:46 UTC
Labels: status: unconfirmed
