### ISSUE TITLE
libqtile problem

### ISSUE THREAD

**Issue by jayjamesdr** [qtile/qtile#2814] opened 2021-09-23 11:21 UTC
2021-09-23 14:18:52,521 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 658, in wait_for_reply
    self._process_error(error_p[0])
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 332, in reply
    data = self.conn.wait_for_reply(self.sequence)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-23 14:18:52,526 ERROR libqtile manager.py:finalize():L269 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 260, in finalize
    widget.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 213, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 36, in finalize
    self._free_pixmap()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 116, in _free_pixmap
    self.qtile.core.conn.conn.core.FreePixmap(self._pixmap)
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2863, in FreePixmap
    return self.send_request(54, buf, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-23 14:18:52,527 ERROR libqtile core.py:_xpoll():L321 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 283, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-23 14:18:52,528 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 283, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-23 14:18:52,528 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-23 14:18:52,535 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 210, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 234, in async_loop
    self.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 272, in finalize
    self.core.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 172, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-23 14:18:52,535 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate

**Comment by elParaguayo** [comment] 2021-09-23 11:23
Can you please use the template for posting issues? There's no detail here about what the issue is, what you did, what your config is etc.

**Comment by jayjamesdr** [comment] 2021-09-23 11:25
https://github.com/jayjamesdr/MyArchBoot/tree/main/desktop_manager/qtile this is my config file

**Comment by elParaguayo** [comment] 2021-09-23 11:28
Let's try again. Please use the template:


Please do not ask general questions here! There are [community
contact](https://github.com/qtile/qtile#community) options for that.

If you are suggesting a new feature/enhancement please instead post it on the
discussions board as an idea: https://github.com/qtile/qtile/discussions/categories/ideas


# Issue description


A brief discussion of what failed and how it failed. A description of
what you tried is helpful, i.e. "When I use lazy.kill() on a window I get
the following stack trace" instead of "Closing windows doesn't work".


# Qtile version


Please include the exact commit hash of the version of Qtile that failed.


# Stack traces


Please attach any stack traces found in:

* `~/.xsession-errors`
* `~/.local/share/qtile/qtile.log`


# Configuration


Please include a link or attach your configuration to the issue.




We're not going to read your config and try to guess your problem.

**Closed** 2021-09-23 11:31 UTC

**Comment by elParaguayo** [comment] 2021-09-23 11:35
You don't need to close this. We just need more information to be able to take a look at this.

**Comment by jayjamesdr** [comment] 2021-09-23 12:05
~/.xsession-errors this is empty and I looked here ~/.local/share/qtile/qtile.log and saw an error message I don't know anything else I'm worried I don't know what's wrong 
thanks for helping me ı give up

**Comment by elParaguayo** [comment] 2021-09-23 12:31
Thanks. No need to worry!

Did Qtile stop working or did you just find the errors when you looked in your log? 

Those errors are all close in time to you exiting Qtile so could be related to the shutdown not handling the closing of various connections appropriately. It's messy but isn't necessarily a problem.

**Comment by jayjamesdr** [comment] 2021-09-23 12:44
yes ı reboot my computer and see this log anyway thanks ı hope this not problem

**Comment by elParaguayo** [comment] 2021-09-23 12:45
Ah, ok. I don't think this is a problem other that we're missing some code to handle shutdown more gracefully.

Thanks for reporting.
