### ISSUE TITLE
Qtile breaks my terminal (alacritty)

### ISSUE THREAD

**Issue by ahmedkhalf** [qtile/qtile#2204] opened 2021-02-11 07:51 UTC
# Issue description

No better way to describe than a video:

https://user-images.githubusercontent.com/36672196/107612293-5cd3a800-6c5f-11eb-97b4-8e889295e9e1.mp4

# Reproduce

1. Use default config
2. Make sure you are in columns layout
3. Spawn 3 alacritty terminals
4. Open an interactive terminal app such as htop or ranger, 
5. Bring the terminal to the right on a new column, and interact with the terminal app, everything suddenly breaks.

# Qtile version

Master Branch (0.16.2.dev230+g0a61002a)

**Comment by m-col** [comment] 2021-02-11 10:01
Do you get log output?

**Comment by cjoke** [comment] 2021-02-11 10:39
looks like something happen inside ranger, and it does'nt looks like something is broken, it just shows filenames over two rows/lines since there is not  space enough. 
What happens when you close the other two terminals ?

**Comment by ahmedkhalf** [comment] 2021-02-11 10:58
> looks like something happen inside ranger, and it doesn't looks like something is broken, it just shows filenames over two rows/lines since there is not space enough.

That's the problem terminal apps aren't receiving a resize signal, making them think the terminal is larger than it is...

And here is a screenshot with htop (same problem):
![image](https://user-images.githubusercontent.com/36672196/107627644-07a49000-6c79-11eb-9134-040d1c225c1d.png)


> What happens when you close the other two terminals ?

![image](https://user-images.githubusercontent.com/36672196/107628041-83064180-6c79-11eb-8ade-9ff720a5ff1c.png)

Still the terminal app doesn't resize.

**Comment by ahmedkhalf** [comment] 2021-02-11 11:00
> Do you get log output?

I'm not sure how that would help, but I will edit my issue to include them.

**Comment by m-col** [comment] 2021-02-11 11:06
Well the logs are where you would see an error message if, for example, qtile was trying to send a configure notify signal but couldn't for whatever reason. That's the terminal probably uses to reconfigure the dimensions of what it is showing.

I guess this only happens with alacritty?

**Comment by ramnes** [comment] 2021-02-11 11:07
Duplicate of #2167

Also discussed here, with a workaround: https://groups.google.com/g/qtile-dev/c/mjMKB533GNA/m/f0UGhBxpDgAJ

And here: https://github.com/qtile/qtile/discussions/2164

**Closed by ramnes** 2021-02-11 11:07 UTC

**Comment by Wisehh** [comment] 2021-10-04 03:03
Sorry for the necrobumping, but I had this trouble today an maybe what I found can help someone else.

In my case, it was insufficient with adding

```
unset COLUMNS
unset LINES
```
to my .zshrc, because for some reason the lazy.spawn command wasn't loading those environment variables. So to ensure they loaded, I found two options:

-  Create the keybinding with the command

`lazy.spawn("zsh -c 'unset COLUMNS; unset LINES; kitty ranger'")`

Which will unset the environment variables BEFORE the command is executed.

- Add to your .zshenv file (or create one, or look for an equivalent in your shell)  the lines
```
unset COLUMNS
unset LINES
```
And after that, you can run your keybinding just with a lazy.spawn("zsh -c 'kitty ranger'")
