### ISSUE TITLE
Window toggled to tiling ignores theme

### ISSUE THREAD

**Issue by waltereikrem** [qtile/qtile#1797] opened 2020-06-29 23:58 UTC
# Issue description
Ive been searching around for a few weeks now. And cant find anything that helps me. i might be missing something, or formatting my search wrong. idk, english isnt my first language so i have some struggles there at times. but...

My issue is that when i toggle a window into floating. the theme i have for my windows dont seem to apply to it.
Also. I have a workspace where floating is the default. When i spawn a window in that workspace, the window spawn with the correct theme. But as soon as i move it or resize it... same thing happens there.  I have some screenshots under of how the floating window thing looks. im sorry if this is very obvious how to fix. i just cant find out how to fix it by my self. thanks for any help of pointers

![floating](https://i.imgur.com/obM1IdU.png)
![not floating](https://i.imgur.com/Qfi7yAc.png)

# Qtile version
Output after running qtille --version:
0.15.1

# Configuration
[My config](https://github.com/waltereikrem/DOTFILES/blob/master/qtile/config.py)

**Comment by tych0** [comment] 2020-06-30 02:17
Are you on master? This seems like it might be a dupe of #1794

**Comment by waltereikrem** [comment] 2020-06-30 15:03
im not sure what it means to e on master. but ill have a look at that link and see if that fix works

**Comment by waltereikrem** [comment] 2020-06-30 15:30
I dont know where to look to find the files i then need to edit im afraid. and google gives me no help. all i get is results for the built in layouts from the docs. and DistroTubes gitlab page.

but if others have had issues like this and it got fixed. maybe it would work to just back up my config and such. and reistall qtile directly from here. as i think i installed from the AUR, and that package might be out of date?

Still strange tho. because when i googled a few days ago. i found youtube videos from years ago where it worked fine to just toggle floating, and move a window around.

and also. my widows do spawn with borders. but just not the borders i set.
- when i toggle a window to float it gets default borders.
- when spawn a window in my floating workspace, it spawns with ccorrect borders. but when moved or resized, it goes back to default borders.

its almost as if floating windows ignores my config. but at the same time not, as my bindings to pop it back in works, my mouse settings for them works even. xD

under you can see my theme settings and such. maybe i made a mistake here?

`##### DEFAULT THEME SETTINGS FOR LAYOUTS #####
layout_theme = {
                "border_width": 3,
                "margin": 25,
                "border_focus": "d7af87",
                "border_normal": "1b1519"
                }

##### THE LAYOUTS #####
layouts = [
    layout.MonadTall(**layout_theme),
    layout.Max(**layout_theme),
    layout.Tile(shift_windows=True, **layout_theme),
    layout.Floating(**layout_theme)
]`

**Comment by ramnes** [comment] 2020-07-01 06:10
Hello @waltereikrem!

You need to pass your theme to the floating layout used by Qtile when doing such actions, which is the one defined in `floating_layout`. Also, `Floating` is not a "real" layout; it don't really make sense to have it in the `layouts` list (have a look at discussions in #1500 and #1444).

```diff
@@ -273,7 +273,6 @@
     layout.MonadTall(**layout_theme),
     layout.Max(**layout_theme),
     layout.Tile(shift_windows=True, **layout_theme),
-    layout.Floating(**layout_theme)
 ]
 
 ##### COLORS #####
@@ -578,7 +577,7 @@
     {'wname': 'branchdialog'},  # gitk
     {'wname': 'pinentry'},  # GPG key password entry
     {'wmclass': 'ssh-askpass'},  # ssh-askpass
-])
+], **layout_theme)
 auto_fullscreen = True
 focus_on_window_activation = "smart"
```

I'll go ahead and close this, but feel free to comment if it's still a problem for some reason. :)

**Closed by ramnes** 2020-07-01 06:10 UTC

**Comment by waltereikrem** [comment] 2020-07-01 14:51
OMG it worked! it  kinda borked when i removed the layout from my list tho. it all froze, the bar, and my bindings would not work.
so i just kept it. it might be me just forgetting a comma or something. but adding the theme variable down at the list of all floating windows worked. dude the relieff lmao. all that googleing for just moving that one variable down a few lines haha. thanks so much for the help guys!
