### ISSUE TITLE
lazy.restart does not restart the qtile

### ISSUE THREAD

**Issue by parsrch** [qtile/qtile#1566] opened 2020-03-27 01:35 UTC
I don't know why but the lazy.restart does a log out instead of reloading config even with the default config.sorry for the lack of info im a newbie in python

**Comment by tych0** [comment] 2020-03-27 03:23
Can you post ~/.xsession-errors?

**Comment by tych0** [comment] 2020-03-27 03:23
And your config would also be helpful.

**Comment by Redcroft** [comment] 2020-03-27 10:01
I'm also having the same issue on latest git version, and there is no xsession-errors file generated. Config file is attached
[config.log](https://github.com/qtile/qtile/files/4392693/config.log)

Thanks

**Comment by parsrch** [comment] 2020-03-27 12:20
> Can you post ~/.xsession-errors?

no errors there also i even tried the default config

**Comment by tych0** [comment] 2020-03-27 13:39
On Thu, Mar 26, 2020 at 06:35:15PM -0700, parsrch wrote:
> I don't know why but the lazy.restart does a log out instead of reloading config even with the default config.sorry for the lack of info im a newbie in python

What happens if you revert 8e249464572b34f88dc78ca420f864baf726690d ?

**Comment by parsrch** [comment] 2020-03-28 07:22
> On Thu, Mar 26, 2020 at 06:35:15PM -0700, parsrch wrote: I don't know why but the lazy.restart does a log out instead of reloading config even with the default config.sorry for the lack of info im a newbie in python
> What happens if you revert [8e24946](https://github.com/qtile/qtile/commit/8e249464572b34f88dc78ca420f864baf726690d) ?

how?

**Comment by parsrch** [comment] 2020-03-28 12:48
> On Thu, Mar 26, 2020 at 06:35:15PM -0700, parsrch wrote: I don't know why but the lazy.restart does a log out instead of reloading config even with the default config.sorry for the lack of info im a newbie in python
> What happens if you revert [8e24946](https://github.com/qtile/qtile/commit/8e249464572b34f88dc78ca420f864baf726690d) ?

the problem was from that commit.thanks,closing issue now

**Comment by tych0** [comment] 2020-03-28 14:28
Can you elaborate? That commit seems to work just fine for me, including calling lazy.restart(). Can you post your config and ~/.xsession-errors?

**Comment by parsrch** [comment] 2020-03-28 16:16
> Can you elaborate? That commit seems to work just fine for me, including calling lazy.restart(). Can you post your config and ~/.xsession-errors?

I tried with the default config and it still had the issue also no errors in .xsession-errors

**Comment by m-col** [comment] 2020-03-29 20:52
I'm getting the same issue from the same commit. This happens with this keybinding:
```
'M-S-r':        lazy.restart(),
```
and also with the shell command:
```
qtile-cmd -o cmd -f restart
```
which outputs:
```
Traceback (most recent call last):
  File "libqtile/ipc.py", line 84, in libqtile.ipc._IPC.unpack
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcol/.local/bin/qtile-cmd", line 11, in <module>
    load_entry_point('qtile==0.14.2', 'console_scripts', 'qtile-cmd')()
  File "libqtile/scripts/qtile_cmd.py", line 205, in libqtile.scripts.qtile_cmd.main
  File "libqtile/scripts/qtile_cmd.py", line 143, in libqtile.scripts.qtile_cmd.run_function
  File "libqtile/command_client.py", line 179, in libqtile.command_client.InteractiveCommandClient.__call__
  File "libqtile/command_interface.py", line 221, in libqtile.command_interface.IPCCommandInterface.execute
  File "libqtile/ipc.py", line 215, in libqtile.ipc.Client.send
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "libqtile/ipc.py", line 161, in libqtile.ipc._ClientProtocol.eof_received
  File "libqtile/ipc.py", line 89, in libqtile.ipc._IPC.unpack
libqtile.ipc.IPCError: error reading reply! (probably the socket was disconnected)
```
I don't have a ~/.xsession-errors and nothing appears in ~/.local/share/xorg/Xorg.0.log either.

Hope this helps.

**Comment by tych0** [comment] 2020-03-30 00:21
Any chance you can put some debugging logs in there to see what's happening? Unfortunately, I can't reproduce :(

**Comment by m-col** [comment] 2020-03-30 08:15
qtile -l  DEBUG outputs these:
```
2020-03-30 09:11:25,021 DEBUG libqtile command_interface.py:call():L301 Command: restart((), {})
2020-03-30 09:11:25,022 DEBUG libqtile manager.py:stop():L258 Stopping qtile
2020-03-30 09:11:25,028 DEBUG libqtile xcore.py:remove_listener():L190 Removing io watch
2020-03-30 09:11:25,029 DEBUG libqtile ipc.py:close():L328 Stopping server on server close
```
But through xephyr I get:
```
Traceback (most recent call last):
  File "/home/mcol/git/qtile/scripts/../bin/qtile", line 33, in <module>
    qtile.main()
  File "/home/mcol/git/qtile/libqtile/scripts/qtile.py", line 147, in main
    q.loop()
  File "/home/mcol/git/qtile/libqtile/core/session_manager.py", line 47, in loop
    self.qtile.loop()
  File "/home/mcol/git/qtile/libqtile/core/manager.py", line 241, in loop
    self._eventloop.run_until_complete(self.async_loop())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
/usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
```

**Comment by tych0** [comment] 2020-03-30 15:29
On Mon, Mar 30, 2020 at 01:15:27AM -0700, m-col wrote:
> qtile -l  DEBUG outputs these:
> ```
> 2020-03-30 09:11:25,021 DEBUG libqtile command_interface.py:call():L301 Command: restart((), {})
> 2020-03-30 09:11:25,022 DEBUG libqtile manager.py:stop():L258 Stopping qtile
> 2020-03-30 09:11:25,028 DEBUG libqtile xcore.py:remove_listener():L190 Removing io watch
> 2020-03-30 09:11:25,029 DEBUG libqtile ipc.py:close():L328 Stopping server on server close
> ```
> But through xephyr I get:
> ```
> Traceback (most recent call last):
>   File "/home/mcol/git/qtile/scripts/../bin/qtile", line 33, in <module>
>     qtile.main()
>   File "/home/mcol/git/qtile/libqtile/scripts/qtile.py", line 147, in main
>     q.loop()
>   File "/home/mcol/git/qtile/libqtile/core/session_manager.py", line 47, in loop
>     self.qtile.loop()
>   File "/home/mcol/git/qtile/libqtile/core/manager.py", line 241, in loop
>     self._eventloop.run_until_complete(self.async_loop())
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
> asyncio.exceptions.CancelledError
> /usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
> ```

Is this with the patch, or without? The patch should catch exactly
this error, I think.

**Comment by m-col** [comment] 2020-03-30 16:09
Oh, my bad, I didn't see the patch sorry - the above was without. Yep it fixes the problem.

**Comment by tych0** [comment] 2020-03-30 16:13
So for you, lazy.restar() with 8e249464572b34f88dc78ca420f864baf726690d restarts correctly?

**Comment by m-col** [comment] 2020-03-30 17:26
8e24946 breaks it, but reverting with the commit on your `revert-shutdown` branch fixes it.

**Comment by Redcroft** [comment] 2020-03-31 11:49
Restarting via qtile-cmd gives the following

`Traceback (most recent call last):
 File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 84, in unpack
  assert len(data) >= HDRLEN
AssertionError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
 File "/usr/bin/qtile-cmd", line 11, in <module>
  load_entry_point('qtile==0.14.2', 'console_scripts', 'qtile-cmd')()
 File "/usr/lib/python3.8/site-packages/libqtile/scripts/qtile_cmd.py", line 201, in main
  ret = run_function(obj, args.function, args.args)
 File "/usr/lib/python3.8/site-packages/libqtile/scripts/qtile_cmd.py", line 143, in run_function
  ret = func(*args)
 File "/usr/lib/python3.8/site-packages/libqtile/command_client.py", line 179, in __call__
  return self._command.execute(self._current_node, args, kwargs)
 File "/usr/lib/python3.8/site-packages/libqtile/command_interface.py", line 221, in execute
  status, result = self._client.send((
 File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 215, in send
  self.loop.run_until_complete(asyncio.wait_for(client_proto.reply, timeout=10))
 File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
  return future.result()
 File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
  return fut.result()
 File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 161, in eof_received
  data, _ = _IPC.unpack(self.recv)
 File "/usr/lib/python3.8/site-packages/libqtile/ipc.py", line 89, in unpack
  raise IPCError(
libqtile.ipc.IPCError: error reading reply! (probably the socket was disconnected)`

**Comment by tych0** [comment] 2020-04-01 14:07
Does https://github.com/tych0/qtile/tree/event-loop-second-try fix it?

**Comment by Redcroft** [comment] 2020-04-03 12:08
That branch works for me, thanks for that :)

**Comment by m-col** [comment] 2020-04-05 20:33
Also fixes it for me.

**Comment by m-col** [comment] 2020-04-13 15:14
Is there a plan to merge the fix or is that just a temporary workaround?

**Comment by tych0** [comment] 2020-04-14 13:23
Just reverted that commit, but I didn't get this bug in the commit message. Should be fixed now, sorry for the breakage everyone :)

**Closed by tych0** 2020-04-14 13:23 UTC
