### ISSUE TITLE
Chromium-based browsers overlap with the Qtile bar.

### ISSUE THREAD

**Issue by ALizarazoTellez** [qtile/qtile#4210] opened 2023-03-25 00:05 UTC
### The issue:

I don't speak English, the following text was generated by an internet translator: I have a problem with Chromium-based browsers (Chrome and Brave, for some reason it didn't happen to me with Opera), and it's that when they start they have an animation with their logos, and in cases (seemingly random, I haven't found a pattern) the logo gets superimposed on the Qtile bar (you can get rid of the error by restarting Qtile) which is annoying, I tried to disable the animations using the flag: -- wm-window-animations-disabled in browsers, but, this didn't work, this happens regardless of whether or not I use a composer. I don't know if this happens in Wayland.

![Fri Mar 24 18:58:38 2023](https://user-images.githubusercontent.com/65132831/227664449-ba6d0a76-b813-434d-81d2-bc24a52983bc.png)

Version: 0.22.1 (From Manjaro Repositories).
Logs: Empty.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by anderson-lt** [comment] 2023-03-25 14:38
I just installed the qtile-git version from the AUR and the error continues.

Version: 0.22.2.dev166+g3fb4910f
Logs: There doesn't seem to be anything relevant, I'm attaching them just in case.

[qtile.log](https://github.com/qtile/qtile/files/11069150/qtile.log)

**Comment by elParaguayo** [comment] 2023-03-25 19:31
We've seen this before but I'm struggling to see how this is happening.

Have you got the systray widget installed? If so, do you get the error if you disable that widget?

**Comment by anderson-lt** [comment] 2023-03-31 13:08
Well, every time I have used the browser without the systray widget, the problem has been eliminated, I just activated the widget again to see if the problem appears again...

**Comment by elParaguayo** [comment] 2023-03-31 13:27
I'm pretty sure this will be the Systray widget but I don't know why chromium based browsers are causing an issue here when the widget behaves correctly for other apps.

It would help if you could provide some steps for recreating this as I can't trigger the issue myself. I also don't know about the animation your referred to in your original post.

**Comment by ALizarazoTellez** [comment] 2023-04-11 01:36
The animation I'm referring to is one that is only seen in the Qtile bar where the error is.

I can't provide the steps because this was happening randomly.

For a few days I re-enabled the systray widget, but the error didn't happen again (no, I didn't update Qtile), also I formatted the laptop and reinstalled Qtile and I haven't seen the error again.

I'll report back later if I see it again, but for now, the error went away for no apparent reason, because I currently have the Systray widget enabled and it's not causing me any problems.

SPANISH.
La animación a la que me refiero es una que solo se ve en la barra de Qtile donde está el error.

No puedo proporcionar los pasos porque esto sucedía de manera aleatoria.

Durante algunos días volví a habilitar el widget de Systray, pero el error no volvío a suceder (no, no actuilicé Qtile), además formatee el computador portátil y volví a instalar Qtile y no he vuelto a ver el error.

Informaré más adelante si lo vuelvo a ver, pero por el momento, el error desapareció sin alguna razón aparente, porque actualmente tengo habilitado el widget de Systray y no me está causando problemas de ningún tipo.

**Comment by elParaguayo** [comment] 2023-04-26 20:31
I'll close this for now (as I can't reproduce the issue). However, feel free to re-open it if you have the issue again.

**Closed by elParaguayo** 2023-04-26 20:31 UTC
Labels: unconfirmed
