### ISSUE TITLE
Qtile doesn't recreate a group with persist to false

### ISSUE THREAD

**Issue by dannycolin** [qtile/qtile#1215] opened 2018-10-19 15:31 UTC
When I set the persist option to `false` on a group and I leave it it is correctly removed. But when I try to move again to that group it doesn't recreate it. Same thing if I try to move a window from let say Group A to a non-persistent Group B.

I use the default settings except for the `groups` var. Here's the modifications I've done: 
```
groups = [
    Group("1", label="term"),
    Group("2", label="www", persist=False),
    # Group 3..4..5..etc... with persist=False
]
```

**Comment by ramnes** [comment] 2018-11-11 00:04
Hi @dannycolin!

"It's not a bug, it's a feature." :smile: 

`persist` is not meant to be used alone, but with dynamic groups, i.e. groups that also have `matches`. See @Roger configuration for example, which uses a lot this mechanism: https://github.com/qtile/qtile-examples/blob/608cbcd1ea642bbe96cc13f2bde852c792e5456b/roger/config.py#L190-L279

I'm closing this issue, but please feel free to open a new one if you feel that `persist` should also have other properties. Thanks!

**Closed by ramnes** 2018-11-11 00:04 UTC
