### ISSUE TITLE
Rofi spawns on the monitor that has the mouse, not focus

### ISSUE THREAD

**Issue by tamis-laan** [qtile/qtile#1419] opened 2019-09-03 07:52 UTC
I trigger rofi with the command `rofi -monitor -1` this tells rofi to open it's window on the currently focused monitor. However rofi opens on the monitor where my mouse cursor is placed and not on the monitor where the focus is. 

This is a fallback mechanism of rofi, thus the information about what monitor is in focus is not being passed allong. How can circumvent this issue?? Is this a bug, or is this feature lacking in qtile?

**Comment by tych0** [comment] 2020-05-11 20:25
I believe this is fixed by #1716

**Comment by owarai** [comment] 2020-12-01 02:51
Same problem here. 
monitor A, B. 
I write something in vim on monitor B which focused on group 2, same time mouse pointer is stil located on monitor A which focused on group 1. Then if I trigger rofi with shortcuts(corresponding command: `rofi show drun -monitor -1`), monitor B auto unfocused and rofi window show up on monitor A. I also set `m: "-1";` in ~/.config/rofi/config.rasi to ensure the global behavior.

> -1 means show rofi on focused monitor. 
> Also try this keybindings on sxhkd, same result.

Maybe this issue should take another look?

**Comment by kaistian** [comment] 2020-12-01 14:50
It's probably because Qtile doesn't support _NET_DESKTOP_VIEWPORT ref this issue davatorium/rofi/issues/1158

**Comment by owarai** [comment] 2020-12-02 06:41
> It's probably because Qtile doesn't support _NET_DESKTOP_VIEWPORT ref this issue [davatorium/rofi/issues/1158](https://github.com/davatorium/rofi/issues/1158)

Yes, output of `xprop -root` lack this property. 

@tych0 . Sorry to bother, could you take a look to confirm this?
If so, is there any plan to support this EWMH property?

**Comment by tych0** [comment] 2020-12-02 13:30
Yeah, looks like that's the issue. I have no plans to implement it, but would be happy to accept a patch with tests that does so.

**Comment by m-col** [comment] 2020-12-09 22:22
The commit in #1991 may fix this, but I am having trouble confirming. When I run `rofi -monitor -1 -show combi -no-config` it tells me it cannot find the viewport information for this desktop, number 3, when I only have two monitors (laptop and one external). Anyone else see this? Could well be a rofi bug but I'm erring more towards me doing something wrong.

**Comment by kaistian** [comment] 2020-12-10 17:35
I'm using an older Qtile #1500 (because of annoying reordering of windows) but don't this it matters for testing this so I patch my files manually.
`_NET_DESKTOP_VIEWPORT(CARDINAL) ` is showing `0, 0` on my left, `2560, 0` in the middle and `5120, 0` on my right monitor.

When my active screen and the mouse is on the same monitor rofi has no errors.
But if my mouse is on one of the screen that is not active I do get errors
```
(process:3479488): X11Helper-DEBUG: 18:24:04.867: Viewport does not exist for current desktop: 6, falling back to mouse location (-5)
(process:3479488): X11Helper-DEBUG: 18:24:04.867: Failed to find monitor, fall back to monitor showing mouse.
(process:3479488): X11Helper-DEBUG: 18:24:04.888: Viewport does not exist for current desktop: 6, falling back to mouse location (-5)
(process:3479488): X11Helper-DEBUG: 18:24:04.888: Failed to find monitor, fall back to monitor showing mouse.
```
And Rofi opens up on the screen my mouse pointer is at.

Your desktop number 3 is you 4th Qtile group, desktop numbers start on 0.
If I run `xprop -root` on my group called "p" I have these 2 lines in the output
```
_NET_CURRENT_DESKTOP(CARDINAL) = 7
_NET_DESKTOP_NAMES(UTF8_STRING) = "a", "s", "d", "www", "u", "i", "o", "p", "n", "io", "scratchpad"
```
So my desktop 7 is the 8th one is the comma separated list.

**Comment by m-col** [comment] 2020-12-10 18:22
Ah, the viewport coordinates _do_ refer to virtual desktops rather than outputs!
This was confusing me. I've just pushed an update. Could you try that please?

**Comment by kaistian** [comment] 2020-12-10 19:53
My `_NET_DESKTOP_VIEWPORT` now looks like this
`_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 2560, 0, 0, 0, 0, 0, 0, 0, 5120, 0, 0, 0, 0, 0, 0, 0`
and the size positions matched the active groups on the screens.

The error message about "viewport does not exist" is not present anymore, but Rofi still open up on the screen the mouse cursor is on and not the active screen.
I have looked at the debug output from Rofi, https://pastebin.com/gEpX5rHH, but can't find any clues there about what could be wrong.

**Comment by tych0** [comment] 2020-12-10 20:10
I think mcol's patch is missing a format=32 in the right place, see my sample for where to put it.

**Comment by m-col** [comment] 2020-12-11 11:57
The format=32 isn't necessary because I added _NET_DESKTOP_VIEWPORT to the
PropertyMap. Hmm, not sure what the try next.

**Comment by tych0** [comment] 2020-12-11 12:09
Ok, it looks like the encoding is busted somehow though. You all the extra coordinates make me think pack_list isn't doing exactly what it should.

**Comment by kaistian** [comment] 2020-12-11 14:31
I did try to add the format=32 yesterday, but Qtile crashed and I could not get it to start after removing it, so I went to bed.
The traceback mention xcore.py and xcffib and might be because `xcore.cpython-38.pyc` would not get updated after i change `xcore.py`, so I deleted the pyc and second time I tried to start Qtile it started, for all I know it might be unrelated.

And now when I test rofi it works with the patch, Rofi is starting one the screen that is active and not where the mouse is :-D

Maybe my test methodology is flawed?
What I did was changing `xcbq.py`, 'xcore.py' and triggered `lazy.restart()`

**Comment by kaistian** [comment] 2020-12-11 14:55
After using the patch I see the following issue, when the Rofi window appears on the active screen the active screen changes to the screen where the mouse is.
Tried setting `focus_on_window_activation = "never"` that did not help.

**Comment by m-col** [comment] 2020-12-19 17:36
As far as I can tell, the patch #1991 does set the hint correctly, as supported by `wmctrl -d` giving me what I would expect:
```
0  * DG: N/A  VP: 0,0     WA: N/A  1
1  - DG: N/A  VP: 0,0     WA: N/A  2
2  - DG: N/A  VP: 0,0     WA: N/A  3
3  - DG: N/A  VP: 1920,0  WA: N/A  q
4  - DG: N/A  VP: 0,0     WA: N/A  w
5  - DG: N/A  VP: 0,0     WA: N/A  e
6  - DG: N/A  VP: 0,0     WA: N/A  scratchpad
```
Can anyone confirm rofi does the expected behaviour on a different WM that sets this? If so, does `wmctrl -d` give different information that what I'm seeing?

Or perhaps we need to set more than the viewport geometry, e.g. also the desktop geometry (DG in the output above)?

**Comment by tych0** [comment] 2020-12-20 18:40
Can you show the raw xprop for _NET_DESKTOP_VIEWPORT for the above? This output looks wrong to me:

```
 _NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 2560, 0, 0, 0, 0, 0, 0, 0, 5120, 0, 0, 0, 0, 0, 0, 0
 ```
 
 but perhaps I'm missing something?

**Comment by m-col** [comment] 2020-12-20 19:25
I think that is expected. Mine is:
```
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0, 1920, 0, 0, 0, 0, 0
```
This is 7 virtual desktops (6 groups + scratchpad), x and y for each. Hidden desktops have 0, 0, so all of mine have 0, 0 except the one that is visible on my second screen to the right (x == 1920).

The patch does the same as i3 [here](https://github.com/i3/i3/blob/fff8b0c0e8d85f804147b0da7c3e0aa3040961a3/src/ewmh.c#L89).

**Comment by tych0** [comment] 2020-12-20 21:13
Ah, right you are. I was thinking it was relative to screens, not groups. So ignore all my complaints in this thread :)

**Comment by tych0** [comment] 2021-01-17 18:15
Ping - any thoughts on this?

**Comment by m-col** [comment] 2021-01-17 19:32
I've revisited it a couple times in the past few weeks but none of the changes we've suggested/discussed here including https://github.com/qtile/qtile/pull/1991 don't seem to fix the problem. As a result I'm not really sure how to proceed.

**Comment by vicrdguez** [comment] 2021-03-30 18:04
Could be an ugly workaround but, something like this could work?
Not working for me now and not a python programmer but I'm trying with this:
```python
def current_screen_index():
    print(str(qtile.screens.index(qtile.current_screen)))
    return str(qtile.screens.index(qtile.current_screen))
```
and then 
```python
 
    Key([mod, "shift"], "Return",
        lazy.spawn("rofi -show drun -monitor " + current_screen_index()),
        #lazy.spawn("rofi -show combi"),
        desc="Open rofi"
        ),
```

**Comment by ramnes** [comment] 2021-03-31 08:55
Is it still an issue? I can't replicate.

**Comment by elParaguayo** [comment] 2022-01-13 22:00
Better late than never...

I've done some digging on this and have some good news. @m-col's patch for adding `_NET_WM_VIEWPORT` works (although I think it also needs to be added to `_NET_SUPPORTED`). Running xprop gave me:

```
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x1200002
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x600002, 0x1200002
_NET_CLIENT_LIST(WINDOW): window id # 0x600002, 0x1200002
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x800000
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x800000
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 1920, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2", "3", "4", "5", "6", "7", "scratchpad"
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 8
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x40011d
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_CURRENT_DESKTOP, _NET_DESKTOP_VIEWPORT, _NET_ACTIVE_WINDOW, _NET_SUPPORTING_WM_CHECK, _NET_WM_NAME, _NET_WM_VISIBLE_NAME, _NET_WM_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_WINDOW_TYPE, _NET_WM_STATE, _NET_WM_STRUT_PARTIAL, _NET_WM_PID, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_STATE_MODAL, _NET_WM_STATE_STICKY, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SHADED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_STATE_FOCUSED
RESOURCE_MANAGER(STRING) = "XTerm.vt100.faceName:\tDejaVu Sans Mono:style=Book:antialias=false\nXTerm.vt100.faceSize:\t12\nXTerm.vt100.reverseVideo:\ttrue\n"
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "gb", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 2
`

I have tested this on two monitors and, when passing `-monitor -1`, it correctly identifies the viewport. The rofi developers added some extra debugging to show this:

```
(process:432947): X11Helper-DEBUG: 21:58:43.616: Query RANDR for monitor layout.
(process:432947): X11Helper-DEBUG: 21:58:43.617: Randr XCB api version: 1.6.
(process:432947): X11Helper-DEBUG: 21:58:43.617: Found randr version: 1.5
(process:432947): X11Helper-DEBUG: 21:58:43.620: Found window manager: |LG3D|
(process:432947): X11Helper-DEBUG: 21:58:43.690: Monitor active
(process:432947): X11Helper-DEBUG: 21:58:43.691: Monitor lookup  by name : -1
(process:432947): X11Helper-DEBUG: 21:58:43.691: Monitor lookup  by name failed: -1
(process:432947): X11Helper-DEBUG: 21:58:43.691: Monitor id: -1
(process:432947): X11Helper-DEBUG: 21:58:43.691: rofi on current monitor
(process:432947): X11Helper-DEBUG: 21:58:43.691: Found current desktop: 0
(process:432947): X11Helper-DEBUG: 21:58:43.691: Found 8 number of desktops
(process:432947): X11Helper-DEBUG: 21:58:43.691: Found viewport for desktop: 0 0
(process:432947): X11Helper-DEBUG: 21:58:43.691: Found monitor @: 0 0 1920x1080
(process:432947): X11Helper-DEBUG: 21:58:43.693: Monitor active
(process:432947): X11Helper-DEBUG: 21:58:43.717: Monitor active
(process:432947): X11Helper-DEBUG: 21:58:44.789: Cleaning up XCB and XKB
```

**Comment by kaistian** [comment] 2022-01-14 15:20
I my second to last comment I did mention it work, but in my last comment I wrote this
`After using the patch I see the following issue, when the Rofi window appears on the active screen the active screen changes to the screen where the mouse is.`

This you test for that?

**Comment by m-col** [comment] 2022-01-14 16:13
> Sorry, I missed that comment. However, that doesn't happen for me. The window opens on the focused screen and that screen remains focused.

Even if you mouse is on the other screen?

**Comment by elParaguayo** [comment] 2022-01-14 16:29
Yes.

I rebased #1991 against current Master so it's either fixed their or I'm doing something wrong.

I take it that you're still seeing that bug then...

**Comment by m-col** [comment] 2022-01-14 17:03
I hadn't test, sorry, just curious. Sounds like you fixed it though. I'll give it a try tonight with my external. Did you push the change to the PR?

**Comment by elParaguayo** [comment] 2022-01-14 17:06
I don't think I "fixed" anything, your PR works unmodified (other than the rebasing which I didn't push). 

I did add `_NET_DESKTOP_VIEWPORT` to `_NET_SUPPORTED` as I think it should be included but it seems to work fine without it.

**Comment by m-col** [comment] 2022-01-14 17:09
Oh lol sorry I completely misread. Then maybe it was a bug in rofi? Pretty interesting.

**Comment by m-col** [comment] 2022-01-17 18:14
https://github.com/qtile/qtile/pull/1991 was merged so this should be fixed.

**Closed by m-col** 2022-01-17 18:14 UTC
Labels: bug, multimonitor, X11
