### ISSUE TITLE
toggle_fullscreen always restore the floating/scratchpad windows to tiling windows

### ISSUE THREAD

**Issue by c02y** [qtile/qtile#4394] opened 2023-08-12 02:02 UTC
### The issue:

`qtile 0.22.2.dev210+g989dde04`
`Arch Linux`
`Python 3.11.3`

When I tried to `toggle_fullscreen` the floating window or scratchpad/dropdown window, and toggle it back to the old status, the window will become tiling status, it won't be a floating window unless I make it floating manually again. If it is a scratchpad/dropdown window, it will be removed from the scratchpad, since if I launch the scratchpad using a keybinding, it will launch a new scratchpad of it.

`toggle_maximize` is the same, I think they should respect the windows' old status.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment] 2023-08-13 19:14
Thanks for making the issue! However, it's a duplicate of #2415 so let's track the issue there

**Closed** 2023-08-13 19:14 UTC
Labels: unconfirmed
