### ISSUE TITLE
Google chrome multi-mon drag/drop regression?

### ISSUE THREAD

**Issue by puntium** [qtile/qtile#1257] opened 2019-01-05 05:40 UTC
Experiencing an issue where drag and drop interactions stop working in Google Chrome under multi-screen configurations.

Repro steps for me:
1) run qlite 0.13.0 (installed from pip). Running on Ubuntu 18.04.1 LTS. (lenovo t480s, though likely not relevant)
2) load in single screen configuration. Run google chrome v71. Open multiple tabs. Drag tabs within the tab bar the change order of tabs. See that this works. Also open bookmark manager (ctrl + shift + o) and see that you are able to reorder bookmarks using drag + drop.
3) Plug in an external monitor. Use xrandr to enable external monitor. Restart qtile so that screens re-configure.
4) Repeat steps in #2 with google chrome. On my system, now dragging a tab always results in a "detached" window, and I am unable to reorder tabs within the same window.
5) Go to the bookmark manager in chrome with Ctrl+shift+o. Observer that dragging bookmarks around to change order has no effect. The black highlight that appears to indicate the new position for a bookmark never appears.

I was also able to verify that v0.10.7 does not repro this behavior for me (under all other same conditions)

**Comment by ramnes** [comment] 2019-01-06 01:09
Looks like a regression, indeed. We had several issues related to Chrome tabs (#408 #615) but here, the fact that it only happens with multiple monitors is very interesting. Does it works again if you go back to one monitor?

**Comment by ramnes** [comment] 2019-01-06 01:37
Do you think you could try to install some previous versions and check if some of those work? A `git bisect` on the repository would be ideal.

**Comment by puntium** [comment] 2019-01-10 21:41
An update on this, it seems like I can actually trigger this issue on qtile 0.10.7 as well. I haven't totally narrowed down the sequence of steps to repro it unfortuantely, but I have seen it happen multiple times.

**Comment by stanso** [comment] 2019-08-06 03:24
It looks like this is still not fixed in the latest release 0.14.2.
In my case, I can trigger it just by open multiple Chrome windows on different screens.
Then I can only drag tabs around on one of those windows. On the other window, dragging would immediately open a new window and could not be merged back. Reloading the config does not help either.

**Comment by ramnes** [comment] 2023-10-10 12:36
A lot I've changed since in both Chrome and Qtile, so I'll go ahead and close this one (I can't reproduce it). Please tell me if you're still hitting this and I'll reopen. :)

**Closed by ramnes** 2023-10-10 12:36 UTC
Labels: kind: bug, area: multimonitor
