### ISSUE TITLE
Problem with spawn

### ISSUE THREAD

**Issue by vslinko** [qtile/qtile#669] opened 2015-05-16 14:59 UTC
After I'm updated to 0.9.1 I've got problem with spawning `terminator`. I'm tried to fix terminator config, but after some minutes I found that terminator works well when I'm starting it from xterm.

So, I'm tried to found a problem:
```
$ touch ter.log
$ echo "date >> /home/vslinko/ter.log" > /usr/bin/ter
$ chmod a+x /usr/bin/ter
$ ter
$ cat ter.log
Sat May 16 17:56:26 MSK 2015
$ # Running /usr/bin/ter using `widget.Prompt()`
$ cat ter.log
Sat May 16 17:56:26 MSK 2015
$ # Running /usr/bin/ter using `Key(['mod4'], 'Return', lazy.spawn('/usr/bin/ter'))`
$ cat ter.log
Sat May 16 17:56:26 MSK 2015
$ ter
$ cat ter.log
Sat May 16 17:56:26 MSK 2015
Sat May 16 17:59:22 MSK 2015
```

**Comment by vslinko** [comment] 2015-05-16 15:00
Other programs like `xterm` and `google-chrome-stable` starting well

**Comment by vslinko** [comment] 2015-05-16 15:03
My config.py:
```py
from libqtile import layout, bar, widget, hook
from libqtile.command import lazy
from libqtile.config import Key, Group, Match, Screen
import subprocess
import os


keys = [
    # Qtile management
    Key(['mod4', 'control'], 'w', lazy.shutdown()),
    Key(['mod4', 'control'], 'r', lazy.restart()),

    # Layout management
    Key(['mod4'], 'Tab', lazy.layout.next()),
    Key(['mod4'], 'apostrophe', lazy.nextlayout()),

    Key(['mod4'], 'Down', lazy.layout.down()),
    Key(['mod4'], 'Up', lazy.layout.up()),

    Key(['mod4'], 'Right', lazy.screen.nextgroup()),
    Key(['mod4'], 'Left', lazy.screen.prevgroup()),

    #Key(['mod4', 'shift'], 'j', lazy.layout.shuffle_down()),
    #Key(['mod4', 'shift'], 'k', lazy.layout.shuffle_up()),

    Key(['mod4'], 'bracketleft', lazy.layout.normalize()),
    Key(['mod4'], 'bracketright', lazy.layout.maximize()),

    Key(['mod4'], 'equal', lazy.layout.grow()),
    Key(['mod4'], 'minus', lazy.layout.shrink()),

    # Windows management
    Key(['mod4'], 'w', lazy.window.kill()),
    Key(['mod4'], 'r', lazy.spawncmd()),
    Key(['mod4'], 'Return', lazy.spawn('/usr/bin/ter')),
    Key(['mod4', 'shift'], 'c', lazy.spawn('google-chrome-stable')),
]


groups = [
    Group('Terminals'),
    Group(
        name='Editor',
        matches=[Match(wm_class=['Emacs'])],
    ),
    Group(
        name='Browser',
        matches=[Match(wm_class=['Google-chrome-stable'])],
    ),
    Group('O1'),
    Group('O2'),
    Group('O3'),
]

for i, group in enumerate(groups):
    no = str(i + 1)
    keys.append(Key(['mod4'], no, lazy.group[group.name].toscreen()))
    keys.append(Key(['mod4', 'shift'], no, lazy.window.togroup(group.name)))


layouts = [
    layout.MonadTall(),
    layout.Max(),
    layout.RatioTile(
        border_focus='ff0000',
    ),
    layout.TreeTab(
        bg_color='cccccc',
        active_bg='505050',
        inactive_bg='909090',
        font='Droid Sans Mono',
        section_fg='000000',
    ),
]


bottom_bar = bar.Bar(
    widgets=[
        widget.GroupBox(
            active='000000',
            inactive='000000',
            borderwidth=1,
            rounded=False,
            this_current_screen_border='000000',
            padding=2,
        ),
        widget.Sep(),
        widget.WindowName(),
        widget.Prompt(),
        widget.Systray(),
        widget.Notify(),
        widget.Sep(),
        widget.CurrentLayout(),
        widget.Sep(),
        widget.Pacman(unavailable='000000'),
        widget.Sep(),
        widget.KeyboardLayout(
            configured_keyboards=['us', 'ru'],
        ),
        widget.Sep(),
        widget.Clock(
            format='%Y-%m-%d %H:%M:%S',
        ),
        widget.Sep(),
        widget.Battery(
            format='{char}{percent:2.0%}',
            charge_char='+',
            discharge_char='-',
        ),
    ],
    size=27,
    background='cccccc',
)

#top_bar = bar.Bar(
#    widgets=[
#        #widget.Wallpaper(),
#    ],
#    size=27,
#    background='cccccc',
#)

screens = [
    Screen(
        #top=top_bar,
        bottom=bottom_bar,
    ),
]


widget_defaults = dict(
    font='Droid Sans',
    fontsize=14,
    foreground='000000',
    padding=3,
)

follow_mouse_focus = False

float_windows = set([])


@hook.subscribe.startup
def vboxclient():
    if os.path.isfile('/usr/bin/VBoxClient-all'):
        subprocess.Popen(['/usr/bin/VBoxClient-all'])
```

**Comment by vslinko** [comment] 2015-05-16 15:05
I'm running qtile on archlinux inside virtualbox

**Comment by vslinko** [comment] 2015-05-16 15:09
.qtile.log:
```
$ cat .qtile.log
2015-05-16 18:07:51,299 WARNING init_log:93 Starting Qtile
2015-05-16 18:07:51,559 WARNING safe_import:49 Can't Import Widget: '.mpriswidget.Mpris', No module named 'dbus'
2015-05-16 18:07:51,560 WARNING safe_import:49 Can't Import Widget: '.mpris2widget.Mpris2', No module named 'dbus'
2015-05-16 18:07:51,560 WARNING safe_import:49 Can't Import Widget: '.mpdwidget.Mpd', No module named 'mpd'
2015-05-16 18:07:51,564 WARNING safe_import:49 Can't Import Widget: '.wlan.Wlan', No module named 'pythonwifi'
2015-05-16 18:07:51,564 WARNING safe_import:49 Can't Import Widget: '.google_calendar.GoogleCalendar', No module named 'httplib2'
2015-05-16 18:07:51,565 WARNING safe_import:49 Can't Import Widget: '.imapwidget.ImapWidget', No module named 'keyring'
2015-05-16 18:07:51,567 WARNING register:102 Registering update without any dbus connection existing
2015-05-16 18:07:51,667 WARNING setup_python_dbus:261 importing dbus/gobject failed, dbus will not work.
```

**Comment by tych0** [comment] 2015-05-16 15:43
On Sat, May 16, 2015 at 07:59:48AM -0700, Vyacheslav Slinko wrote:
> After I'm updated to 0.9.1 I've got problem with spawning `terminator`. I'm tried to fix terminator config, but after some minutes I found that terminator works well when I'm starting it from xterm.
> 
> So, I'm tried to found a problem:
> ```
> $ touch ter.log
> $ echo "date >> /home/vslinko/ter.log" > /usr/bin/ter
> $ chmod a+x /usr/bin/ter
> $ ter
> $ cat ter.log
> Sat May 16 17:56:26 MSK 2015
> $ # Running /usr/bin/ter using `widget.Prompt()`
> $ cat ter.log
> Sat May 16 17:56:26 MSK 2015
> $ # Running /usr/bin/ter using `Key(['mod4'], 'Return', lazy.spawn('/usr/bin/ter'))`
> $ cat ter.log
> Sat May 16 17:56:26 MSK 2015
> $ ter
> $ cat ter.log
> Sat May 16 17:56:26 MSK 2015
> Sat May 16 17:59:22 MSK 2015
> ```

You need a shebang for this to work right, i.e.

```
echo "#!/bin/bash" >> ter
echo "date >> /home/vslinko/ter.log" >> ter
```

qtile just execs stuff via execvp, so the kernel doesn't know what to
do with something that doesn't have a shebang and it fails.

What's your error when spawning terminator?

**Comment by vslinko** [comment] 2015-05-16 15:52
yes, shebang is helps with `ter` but `terminator` has shebang:
```
$ cat /usr/bin/terminator | head -1
#!/usr/bin/python2
```

I don't get any error, terminator just doesn't start from qtile spawn commands.

**Comment by tych0** [comment] 2015-05-16 15:58
On Sat, May 16, 2015 at 08:52:58AM -0700, Vyacheslav Slinko wrote:
> yes, shebang is helps with `ter` but `terminator` has shebang:
> ```
> $ cat /usr/bin/terminator | head -1
> #!/usr/bin/python2
> ```
> 
> I don't get any error, terminator just doesn't start from qtile spawn commands.

Ah, looks like we don't actually log anything; what if you apply:

http://paste.ubuntu.com/11168534/

and try it?

**Comment by vslinko** [comment] 2015-05-16 16:08
No exception there...

**Comment by vslinko** [comment] 2015-05-16 16:13
Created file test.py:
```
#!/usr/bin/python3

import os

os.execvp("terminator", ["terminator"])
```

xterm opens
qtile spawn doesn't

**Comment by vslinko** [comment] 2015-05-16 16:29
may be problem is in qtile under python3 but terminator runs under python2?

**Comment by tuxitop** [comment] 2015-07-07 12:19
I also have this problem with the latest version of qtile. It's odd.
when running with python3 qtile doesn't run terminator from the prompt widget. It shift+Enter (lazy.spawn("terminator")) also doesn't work.

**Comment by ramnes** [comment] 2015-10-05 15:42
Yep, I can confirm this bug with Qtile current HEAD (e71a127) running under Python 3.4.

**Comment by ramnes** [comment] 2015-10-17 00:11
This is very strange. `os.execvp("terminator", ["terminator"])` works as expected on a Python 3 shell, but not in the `cmd_spawn` context.

**Comment by tych0** [comment] 2015-10-17 00:17
What if you close the stdin and stdout first, does it still missbehave?

**Comment by ramnes** [comment] 2015-10-17 00:38
Yep, it doesn't change anything.

**Comment by ramnes** [comment] 2015-10-17 00:49
Okay, since I don't get the point of 95% of the code in `cmd_spawn`, I reduced it to its minimal state, and it's working correctly: https://gist.github.com/ramnes/b0a394a5efaffd51274c

**Comment by ramnes** [comment] 2015-10-17 00:51
Seriously, is all that stuff just about not logging child output in `.qtile-errors`?

**Comment by tych0** [comment] 2015-10-17 05:36
Yes (assuming you mean. qtile.log). I don't want to see anything in there :-)

**Comment by tych0** [comment] 2015-10-17 05:40
Oh, no. Some of it is correctness; in your version if your exec fails, you'll end up with two qtile pids, which is probably not what you want :-)

**Comment by XiKuuKy** [comment] 2015-10-19 21:52
I also have this problem in my install.

**Comment by flacjacket** [comment] 2015-10-21 04:49
So a minimum example that reproduces this is:
```
import os

term = 'terminator'

os.close(0)
fd = os.open(os.devnull, os.O_RDWR)
os.dup2(fd, 0)

os.execvp(term, [term])
```
Commenting out the `os.dup2` call doesn't change anything. With this script, since only stdin is closed, we still get stderr, and this prints out:
```
ConfigBase::load: Unable to open /home/sean/.config/terminator/config ([Errno 2] No such file or directory: '/home/sean/.config/terminator/config')
/usr/lib64/python2.7/site-packages/terminatorlib/window.py:65: Warning: The property GtkWindow:allow-shrink is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.set_property('allow-shrink', True)
PluginRegistry::load_plugins: Importing plugin __init__.py failed: 'module' object has no attribute 'AVAILABLE'

(terminator:12414): Vte-0.0-CRITICAL **: vte_pty_set_utf8: assertion 'priv->pty_fd > 0' failed
zsh: segmentation fault  python test.py
```
So it looks like there is something in vte that is baulking when it doesn't have stdin. I guess there is no need for us to close stdin when we are spawning, but I could be wrong.

**Comment by flacjacket** [comment] 2015-10-21 05:09
So this fixes terminator for me: https://github.com/flacjacket/qtile/tree/no_close_stdin as long as this isn't inadvertently breaking something, that should be ok.

**Comment by tych0** [comment] 2015-10-21 13:21
On Tue, Oct 20, 2015 at 10:09:03PM -0700, Sean Vig wrote:
> So this fixes terminator for me: https://github.com/flacjacket/qtile/tree/no_close_stdin as long as this isn't inadvertently breaking something, that should be ok.

What if you switch it to /dev/zero instead of /dev/null, does that
help?

**Comment by flacjacket** [comment] 2015-10-21 13:43
That gives the same thing. Looking at the error again, `'priv->pty_fd > 0'` this is probably related to the problem, whatever we're doing closing stdin/out/err, when the execvp runs and opens a fd, it is 0.

**Comment by tych0** [comment] 2015-10-21 13:49
On Wed, Oct 21, 2015 at 06:43:08AM -0700, Sean Vig wrote:
> That gives the same thing. Looking at the error again, `'priv->pty_fd > 0'` this is probably related to the problem, whatever we're doing closing stdin/out/err, when the execvp runs and opens a fd, it is 0.

Hrm. I wonder if the fds are getting a stray O_CLOEXEC somehow? I
don't see where they would be, though. We should be dup2()ing to fd 0,
so I don't see how it would re-opened as a pty fd.

Anyway, it's a minor point, you're probably right that we don't really
need to close stdin, although I'm not sure what happens if you ^C
while running qtile from a terminal (i.e. does the terminal translate
the ^C to SIGINT or does each application do that?). If it's the
terminal, you may have a problem killing qtile in this case via ^C. If
it's the application, as long as terminator DTRT it should be ok. It
really would be better to figure out if there is something wrong with
the stdin closing code, though.

**Comment by flacjacket** [comment] 2015-10-22 15:45
So I don't know for sure, but I think I was still running my branch that didn't close stdin, and I was getting some really weird issues with firefox. Re-installing fixed it, so I don't know exactly, I can look into it again, tho, but we really *should* be closing stdin.

I do know O_CLOEXEC was added to the os module in 3.3, but I wouldn't expect it to be getting that flag on an open.

**Closed** 2015-10-27 18:15 UTC
Labels: bug

**Comment by flacjacket** [comment] 2015-10-27 18:16
So I think I tracked this down, since Python 3.4, the default action is to close file descriptors in children [1]. The most recent commit should remedy this.

[1] https://docs.python.org/3/library/os.html#inheritance-of-file-descriptors

**Comment by ramnes** [comment] 2015-10-27 21:07
Wow, I didn't know that. I will test your commits as soon as I get home, but it obviously looks like the origin of our problems.

**Comment by ramnes** [comment] 2015-10-30 00:45
Yep, I confirm that it's fixed. Thanks!
